### ISSUE TITLE
Allow more detailed control over previous scanned code in continuous mode

### ISSUE THREAD

**Issue by thegnuu** [capacitor-community/barcode-scanner#106]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to reset the previously scanned code when using continuous mode.

**Describe the solution you'd like**
- Add a function to let the user reset the last code (probably the easiest way)

**Describe alternatives you've considered**
- Remove the "cache" and let the user handle it (maybe not ideal)
- Allow to set a time to reset the last scanned code automatically

**Comment by thegnuu** [comment]
@JanMisker what do you think?

**Comment by JanMisker** [comment]
In my use case I just ignore the duplicate code on the javascript side, so in my app, not in the plugin. 

Still a setting could help. I'm not sure whether it makes sense to put a timer on it, seems simpler to tell the plugin to either send or don't send the same code that was scanned just before. If more complicated logic is needed (timeout, don't send N codes back) I'd say it could be solved in the app.

**Comment by thegnuu** [comment]
I think you are right, duplicates should be handled by your own implementation :) For your information, I am currently investigating rewriting the plugin as (currently not really) discussed in #107.

The example apps provided by google provide really promising results....

This would required some breaking changes anyway so I think about completely removing the "not continuous" method and leave the implementation of a single-scan to the user itself. Since the current implementation is technically able to capture multiple codes within the view but only returns the first one found this would make more sense anyway, so you can wait for the codes you really want before closing the reader....

**Comment by thegnuu** [comment]
This will be addressed in the new ml-kit version
