### ISSUE TITLE
Option for limiting which code type(s) can be scanned

### ISSUE THREAD

**Issue by bash88** [capacitor-community/barcode-scanner#11]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to limit the code types that can be scanned. I think this would improve user experience because incompatible code types can't be scanned this way.

**Describe the solution you'd like**
An option in the prepare and/or startScan methods to specify which code type(s) this particular scanner can scan.

**Describe alternatives you've considered**
.

**Additional context**
Example of how the phonegap barcode scanner handled this (formats option):
https://github.com/phonegap/phonegap-plugin-barcodescanner#using-the-plugin

**Comment by tafelnl** [comment]
I like this feature request. Will try to implement within ~7 days.

**Comment by tafelnl** [comment]
Just an update to let you know that I am on it. Work in progress on this branch: https://github.com/DutchConcepts/capacitor-barcode-scanner/tree/feat/support-specifying-formats. Android should already work. The API looks like the following:

`BarcodeScanner.start({ targetedFormats: ['QR_CODE'] })`

All supported types can be found [here](https://github.com/DutchConcepts/capacitor-barcode-scanner/blob/feat/support-specifying-formats/android/src/main/java/com/dutchconcepts/capacitor/barcodescanner/BarcodeScanner.java#L56)

**Comment by rdlabo** [comment]
@tafelnl This is great work. I'm looking forward to merge it!

**Comment by tafelnl** [comment]
First of all I am sorry for letting you wait for so long. Recent lockdown here caused a lot of work to pile up. But I have great news for you: I just released an alpha version with this feature.

Please run `npm i @dutchconcepts/capacitor-barcode-scanner@v1.2.0-alpha.0` to try it out.

**Comment by hellokingdom** [comment]
Brilliant @tafelnl. I've recently swapped to this barcode scanner after initially using the Cordova plugin. Very impressed with the work you have done and seeing great results. This feature is really import to our use case so I'll feedback on our experience.

**Comment by hellokingdom** [comment]
@tafelnl no issues at all with this. Tested on QR Code only and a mix of other barcodes. Great work.
