### ISSUE TITLE
Change permissions text

### ISSUE THREAD

**Issue by jahnavi310** [capacitor-community/barcode-scanner#110]
Hi there,

I am trying to change the permissions text when the user opens the app for the first time. Is there a way that this can be achieved via code? I need to change the main text and not the description since i know that can be changed via info.plist property.

Thanks in advance

**Comment by JanMisker** [comment]
@jahnavi310 what do you mean with 'main text'? Can you post a screenshot?

**Comment by thegnuu** [comment]
A screenshot would really help in that case, but if the text you are describing is the one I am thinking of there is no way to change it. Better usability is usually achieved with a custom UI prior to the `requestPermission` action to prepare the user for the request and add additional information why this is required.

**Comment by thegnuu** [comment]
@jahnavi310 I will close this issue for now, if you have any problems feel free to reopen it or create a new one :)
