### ISSUE TITLE
Blank screen on Android 11

### ISSUE THREAD

**Issue by imDevSalman** [capacitor-community/barcode-scanner#111]
Blank screen appears instead of scanner on android 11 meanwhile it works just fine on android 9.

Mobile: Moto G9
Ionic version: 6.0.12
capacitor version: 3.4.1
capacitor android version: 3.4.3
barcode-scanner version: 2.1.0
https://user-images.githubusercontent.com/76111741/160090837-6a9a33f0-35d5-45f4-9d45-d09149e3b4d5.mp4

**Comment by davidecampello** [comment]
I'm having the same issue.

**Comment by maxsil69** [comment]
Me too :-(

**Comment by imDevSalman** [comment]
> I'm having the same issue.



> Me too :-(
any luck so far?

**Comment by thegnuu** [comment]
Sorry it took me so long to respond!

I was having the same issue on Android at first, I realised that Ionic is somewhere adding a white background with a css variable which is for some reason not happening on iOS. Unfortunately `hideBackground` won't do the full work in that case.

Can you check and make sure that every `div` which is currently in your visible DOM has a transparent background?

**Comment by laurentguenver-a** [comment]
I'm having the same issue. 
Someone has an idea ?

**Comment by thegnuu** [comment]
As I said in my previous comment, have you verified that all the DOM elements are in fact transparent?
For some reason ionic behaves not the same on Android and iOS....

I cannot reproduce this issue in my test project with different Android versions.

If you want me to help in some ways I need additional information or a project to reproduce this issue.
Just "It does not work" unfortunately won't help us to help you ;)

**Comment by imDevSalman** [comment]
> As I said in my previous comment, have you verified that all the DOM elements are in fact transparent? For some reason ionic behaves not the same on Android and iOS....
> 
> I cannot reproduce this issue in my test project with different Android versions.
> 
> If you want me to help in some ways I need additional information or a project to reproduce this issue. Just "It does not work" unfortunately won't help us to help you ;)

Thanks for taking the time to reply, below are the content of my HTML, SCSS and TS file respectively -
Note:- Before posting this comment I tried running this and it worked fine for the first time even on android 11, but when I closed the app and restarted, same issue started to occur.

home.page.html

```
<ion-content [style.--background]="scanBarcode?'transparent':'#fff'">
  <ion-grid>
    <ion-button expand="block" (click)="scanBarcode()" [hidden]="scanActive">Scan</ion-button>
    <div class="scan-box" [hidden]="!scanActive"></div>
    <ion-button expand="block" (click)="stopScan()" [hidden]="!scanActive">Stop Scan</ion-button>
  </ion-grid>
</ion-content>
```

home.page.scss

```
.scan-box {
  border: 2px solid #fff;
  box-shadow: 0 0 0 100vmax rgba(0, 0, 0, 0.5);
  content: "";
  display: block;
  left: 50%;
  height: 300px;
  position: absolute;
  top: 50%;
  transform: translate(-50%, -50%);
  width: 300px;
}
```

home.page.ts

```
import { AfterViewInit, Component } from '@angular/core';
import {
  BarcodeScanner,
  CameraDirection,
} from '@capacitor-community/barcode-scanner';
import { AlertController } from '@ionic/angular';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements AfterViewInit {
  scanActive = false;
  result;

  constructor(private alertController: AlertController) {}

  ngAfterViewInit(): void {
    BarcodeScanner.prepare();
  }

  async scanBarcode() {
    const allowed = await this.checkPermission();
    if (allowed) {
      this.scanActive = true;
      BarcodeScanner.hideBackground();
      const result = await BarcodeScanner.startScan({
        cameraDirection: CameraDirection.BACK,
      });
      if (result.hasContent) {
        this.scanActive = false;
        this.result = result.content;
        console.log(`debug: ${this.result}`);
      }
    }
  }

  stopScan() {
    BarcodeScanner.showBackground();
    BarcodeScanner.stopScan();
    this.scanActive = false;
  }

  async checkPermission() {
    return new Promise(async (resolve, reject) => {
      const status = await BarcodeScanner.checkPermission({ force: true });
      if (status.granted) {
        resolve(true);
      } else if (status.denied) {
        const alert = await this.alertController.create({
          header: 'No Permission',
          message: 'Please allow camera access in your settings.',
          buttons: [
            { text: 'No', role: 'cancel' },
            {
              text: 'Open Settings',
              handler: () => {
                BarcodeScanner.openAppSettings();
                resolve(false);
              },
            },
          ],
        });
        await alert.present();
      } else {
        resolve(false);
      }
    });
  }
}
```

**Comment by thegnuu** [comment]
@imDevSalman Thank you for the additional information, please give me some time to look into it.

Unfortunately I have no Android 11 hardware, I can only test it with an emulator. Do you eventually already know if the issue can be reproduced within emulation?

**Comment by imDevSalman** [comment]
@thegnuu 
I tried reproducing the issue on emulator, but its working as expected in an emulator.

**Comment by thegnuu** [comment]
@imDevSalman Thanks for your fast response! This is bad, at least for me to help you find a solution since I don't have a test device.

Can you see something suspicious in the logs when this issue occurs? It might be as well something related to the permissions, I know that there are some issues if you set the permissions to "Ask every time" as you can see here #66.

**Comment by davidecampello** [comment]
Same to me! Tried on emulator but It's working as expected while we are having emails from customer using android 11 (and one using iphone but I'm not sure it's the same problem).

**Comment by soyardee** [comment]
I happened to run across a similar issue on my android 11 device using angular 12. I haven't tested in the emulator, but I was able to determine that the `<body>` tag in `index.html` where I placed my entry component needs to have a transparent background styling set as well (either via `document.body.style.background = 'transparent';` or adding a css class to the `<body>` tag). For whatever reason, the document body wasn't inheriting from the parent html node as far as I can tell.

**Comment by thegnuu** [comment]
@imDevSalman Thank you for letting me know! For now I don't think that it makes sense to add this by default to the current version of the library since it might break other things and those changes can be easily applied in js by the devs as well (as soon as you find the issue of course ;) ).

I am currently working on a new version of this library which will be breaking anyway, maybe I will apply your changes there to help prevent issues like this in the future!

Glad you found a solution :)

**Comment by lemhteske** [comment]
How can I this workaround from @imDevSalman in Ionic javascript?

**Comment by thegnuu** [comment]
Unfortunately I cannot help you with that since your setup can be completely different event if you use ionic as well. Basically you need to make sure that all DOM elements currently visible have a transparent background, for this you might need to add styles (background and background-color) to some elements or you need to change some css variables which can be easily done with js.
