### ISSUE TITLE
'discoverCaptureDevices()' is deprecated

### ISSUE THREAD

**Issue by portfel-corporation** [capacitor-community/barcode-scanner#120]
**Describe the bug**
'discoverCaptureDevices()' is deprecated, build compiles but gives warning.

Xcode Version 13.3.1 (13E500a)
@capacitor-community/barcode-scanner": "^2.1.1

screenshots 
https://ibb.co/VtNcYKJ
https://ibb.co/MB397sZ

**Comment by thegnuu** [comment]
Yeah, I know about that warning, but for now it can be ignored :)

**Comment by thegnuu** [comment]
This "issue" is now fixed in the ml-kit branch and will be released in the upcoming weeks :)
