### ISSUE TITLE
Can someone please help me with a blank Vue3 Capacitor Ionic - Barcode Scanner Example

### ISSUE THREAD

**Issue by tejavoo** [capacitor-community/barcode-scanner#121]
I have been struggling to get the basic scan and display the QR with Ionic Vue - Capacitor with this Capacitor Plugin

Thanks

**Comment by thegnuu** [comment]
First of all, please use an inspector to verify that all your visible DOM elements have a transparent background, just using `hideBackground` is not enough in most cases. You can easily achieve this by just clicking through your DOM and add `background: transparent` and `background-color: transparent` to all elements. In cases like this there is usually a problem with your setup and not with the plugin itself :)

You can find more information and some discussions here #111

**Comment by thegnuu** [comment]
I will close this issue since I have not got any feedback, feel free to reopen it or create another issue if you still have problems :)
