### ISSUE TITLE
Implement zoom for scanner

### ISSUE THREAD

**Issue by mattiswikar** [capacitor-community/barcode-scanner#123]
If scanning in an environment where one can't get really close up to read the code, it would be nice to have a little bit of zoom in the camera view. Hopefully that could be implemented :)

**Comment by thegnuu** [comment]
I will have a look into this, I am not sure if it is possible at the moment, but I will check it out.

**Comment by juergenriemer** [comment]
Any news on this? That feature is definitely sg I'd love to see!

**Comment by thegnuu** [comment]
I did not have a look at this right now, since I am working on the MLKit version of this plugin and someone just started working on the Android part of this change, since switching to MLKit would change the implementation completely (at least on Android) I am currently holding back additional changes since we will have to do it again once the MLKit version is up and running. But this feature is still in my backlog.

**Comment by thegnuu** [comment]
This feature is implemented in `v5` of the plugin, it will need to be tested fully, but the general functionality is available as pre-release now.

**Comment by sadrataban** [comment]
@thegnuu I tried this feature on v5 and it works well. But the issue is that on v5 the scan functions promise is never fulfilled.

**Comment by thegnuu** [comment]
@sadrataban Thank you for the information, I will check if we can fulfill the promise or if we need to change the definition of the function... Generally speaking, it does not make sense to await a function that requires a callback anyway.

**Comment by sadrataban** [comment]
@thegnuu sorry
You're right. I didn't notice that the method accepts a callback function as a parameter.

I was able to implement it and all is working perfectly. However it seems zooming is not working on Android. Is there anything I'm missing here? Thanks for your help

**Comment by thegnuu** [comment]
This is absolutely possible, I have done a few tests on iOS, but on Android I have not tested it myself, just merged a few PRs (since it is beta anyways ;) )
