### ISSUE TITLE
TO JS undefined

### ISSUE THREAD

**Issue by RyanYangGit** [capacitor-community/barcode-scanner#129]
When i run on ionic6, it doesn't work. The xcode output shows "TO JS undefined", no matter use BarcodeScanner.hideBackground() or BarcodeScanner.startScan().
Is anyone also got this error?

**Comment by thegnuu** [comment]
I have no issues in with my ionic 6 test setup, the plugin works as expected in my case so it might be an issues with your setup and not the plugin itself.

Can you share a repo where I can reproduce your issue?

**Comment by kieranbarlow** [comment]
I'm getting this too. When looking at Xcode I can see a warning:

`discoverCaptureDevices()' is deprecated: New Xcode? Check if `AVCaptureDevice.DeviceType` has new types and add them accordingly.`

**Comment by sjonkeesse** [comment]
Same here

![Xcode log](https://i.ibb.co/yRykjf3/Screenshot-2022-08-16-at-15-36-38.png)

**Comment by sjonkeesse** [comment]
For me this was the issue. 
In `@capacitor-community/barcode-scanner/ios/Plugin/Plugin.swift` the `UIApplication.shared.statusBarOrientation` was not just deprecated, but is obsolete. This line:

```
self.videoPreviewLayer?.connection?.videoOrientation = interfaceOrientationToVideoOrientation(UIApplication.shared.statusBarOrientation)
```

should be replaced to something like this

```
if let interfaceOrientation = UIApplication.shared.windows.first(where: { $0.isKeyWindow })?.windowScene?.interfaceOrientation {
    self.videoPreviewLayer?.connection?.videoOrientation = interfaceOrientationToVideoOrientation(interfaceOrientation)
}
```

The `TO JS undefined` log remains, but the barcode scanner seems to work.

**Comment by BREEZE1987** [comment]
I have gotten the same problem
![20230307162808](https://user-images.githubusercontent.com/3862590/223366282-7aed781e-f1d0-42cf-8a8f-bda69d52a200.jpg)

**Comment by DidoMarchet** [comment]
Me too
<img width="366" alt="Screenshot 2023-03-16 at 15 57 53" src="https://user-images.githubusercontent.com/38940340/225657482-ca83b047-e25d-4815-8555-003054234393.png">
