### ISSUE TITLE
become a capacitor community plugin

### ISSUE THREAD

**Issue by mesqueeb** [capacitor-community/barcode-scanner#13]
I'd love this plugin to be an officially maintained capacitor community plugin!
Lots of people would like this too:
https://github.com/capacitor-community/proposals/issues/53

**Comment by tafelnl** [comment]
I will put effort into making this a community plugin sometime next week! This week I will work on two other issues.

**Comment by cmartinezone** [comment]
> I will put effort into making this a community plugin sometime next week! This week I will work on two other issues.

Thank you for the great work!

**Comment by SalahAdDin** [comment]
@tafelnl It seems it is now a _"community"_ plugin, but it is not installable from **npm** _capacitor-community_ packages.

**Comment by tafelnl** [comment]
Yes, you are correct. I will release the next version on the community npm.

**Comment by SalahAdDin** [comment]
@tafelnl you could also request permissions from the user.

**Comment by mesqueeb** [comment]
@tafelnl looking forward!!

**Comment by tafelnl** [comment]
Just published the package under `@capacitor-community/barcode-scanner`. 🚀

**Comment by mesqueeb** [comment]
@tafelnl it's still `import com.dutchconcepts.capacitor.barcodescanner.BarcodeScanner;` even though it's now not `dutchconcepts` anymore?

**Comment by tafelnl** [comment]
For legacy reasons, yes. But it does not affect the functionality of the app.
