### ISSUE TITLE
Value of optional type 'CAPBridgeProtocol?' must be unwrapped to refer to member 'getWebView' of wrapped base type 'CAPBridgeProtocol'

### ISSUE THREAD

**Issue by asdmx** [capacitor-community/barcode-scanner#130]
**Describe the bug**
Error occured during the XCode compilation

**Expected behavior**
Error displayed : Swift compiler error Value of optional type 'CAPBridgeProtocol?' must be unwrapped to refer to member 'getWebView' of wrapped base type 'CAPBridgeProtocol'

**Screenshots**
<img width="728" alt="Captura de Pantalla 2022-06-23 a la(s) 10 30 07" src="https://user-images.githubusercontent.com/8944370/175337429-a936f603-6d76-4c81-bc62-53a75b84692d.png">
<img width="733" alt="Captura de Pantalla 2022-06-23 a la(s) 10 30 26" src="https://user-images.githubusercontent.com/8944370/175337472-c9ddb814-12ca-450e-a94b-5ec33b1a5808.png">
<img width="734" alt="Captura de Pantalla 2022-06-23 a la(s) 10 30 34" src="https://user-images.githubusercontent.com/8944370/175337519-8cab52c9-ec0f-4bc0-93b6-03f12a65c621.png">

**Desktop (please complete the following information):**

- OS: 11.2.3
- XCODE 12.5.1

Thanks in advance for your help

**Comment by thegnuu** [comment]
@asdmx Unfortunately I have no access to an another Mac with Xcode 12, I am working with Xcode 13 and MacOS 12 for all projects and everything is working without any issues on my devices. Which version of capacitor are you using?

**Comment by asdmx** [comment]
@thegnuu I solve my problem upgrading my MacOS to 12 and my XCODE to 13, but I have to uninstall first and then install again via NPM, thanks for your help

**Comment by thegnuu** [comment]
Glad you were able to resolve your issue and sorry I was not able to help you with the older versions, unfortunately my available testing devices are limited at the moment ;)
