### ISSUE TITLE
Capacitor V4 support

### ISSUE THREAD

**Issue by melihgunduz** [capacitor-community/barcode-scanner#132]
Hello, Capacitor V4 has been released. Do you have any plans for compatibility support?

**Comment by thegnuu** [comment]
Sure thing! I am not in the office for the next 3 weeks but after quick google search and looking at the plugin docs I was not able to see any changes in the plugin interfaces.

Have you already tested it with v4? It might work out of the box or maybe we just need to update the dependencies, I might be able to do this if I am away, might not be much work :)

**Comment by joeldhenry** [comment]
The PR looks good! Can you merge it in & publish?

**Comment by AshleyMedway** [comment]
There are other changes needed for 4.0 support

**Comment by thegnuu** [comment]
v3 with capacitor v4 support is released and ready to use!
