### ISSUE TITLE
Be able to specify the dimensions of the scan view

### ISSUE THREAD

**Issue by csurbier** [capacitor-community/barcode-scanner#136]
It should be nice to avoid having the full screen for scanning and having an option to pass the dimensions (x,y,width,height) of the desired scan view.

In the plugin code, values are hardcoded:
` public override func load() {
        self.cameraView = CameraView(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height))
        self.cameraView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
    }`
 

**Describe the solution you'd like**
Be able to pass the **x,y,width,heigh**t as parameters and the plugin will initialize the CameraView based on those parameters.

Thanks 
Christophe

**Comment by thegnuu** [comment]
@csurbier the `ml-kit` version will be finished soon, and codes scanned there will return the position of the code, therefore you will be able to make sure only codes in a given area will be used
