### ISSUE TITLE
ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by ssj7** [capacitor-community/barcode-scanner#138]
**Describe the bug**
Unable to resolve dependency tree
Fresh installation of everything.

**To Reproduce**

1. npm install @ionic/angular@6 @ionic/angular-server@6
2. ionic start test blank --type angular 
3. cd test
4. npm install @capacitor-community/barcode-scanner
5. See error

**Expected behavior**
install successfully like most updated plugins.

**Screenshots**
<img width="671" alt="Screen Shot 2022-08-08 at 8 30 35 AM" src="https://user-images.githubusercontent.com/4066552/183341308-8733f3b7-c16b-45d4-9e71-8419f5fdd8ab.png">

**Version**
[v2.1.1]

**Desktop (please complete the following information):**

- OS: MacOS Monterey 12.5
- Browser [Firefox]
- Version [103.0.1]

**Additional context**
`# npm resolution error report

2022-08-08T04:15:15.223Z

While resolving: ang@0.0.1
Found: @capacitor/core@4.0.1
node_modules/@capacitor/core
  @capacitor/core@"4.0.1" from the root project

Could not resolve dependency:
peer @capacitor/core@"^3.0.0" from @capacitor-community/barcode-scanner@2.1.1
node_modules/@capacitor-community/barcode-scanner
  @capacitor-community/barcode-scanner@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "@capacitor/core",
    "version": "4.0.1",
    "whileInstalling": {
      "name": "ang",
      "version": "0.0.1",
      "path": "Desktop/Test"
    },
    "location": "node_modules/@capacitor/core",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "prod",
        "name": "@capacitor/core",
        "spec": "4.0.1",
        "from": {
          "location": "Desktop/Test"
        }
      }
    ]
  },
  "currentEdge": {
    "type": "prod",
    "name": "@capacitor/core",
    "spec": "4.0.1",
    "from": {
      "location": "Desktop/Test"
    }
  },
  "edge": {
    "type": "peer",
    "name": "@capacitor/core",
    "spec": "^3.0.0",
    "error": "INVALID",
    "from": {
      "name": "@capacitor-community/barcode-scanner",
      "version": "2.1.1",
      "whileInstalling": {
        "name": "ang",
        "version": "0.0.1",
        "path": "Desktop/Test"
      },
      "location": "node_modules/@capacitor-community/barcode-scanner",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "prod",
          "name": "@capacitor-community/barcode-scanner",
          "spec": "*",
          "from": {
            "location": "Desktop/Test"
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false
}
`

**Comment by rs2-davebanguilan** [comment]
Upgrade to Capacitor 4.0 is still not merged yet. But someone already created a PR here: `https://github.com/capacitor-community/barcode-scanner/pull/137`

**Comment by ssj7** [comment]
> Upgrade to Capacitor 4.0 is still not merged yet. But someone already created a PR here: #137
Thanks I'll try it. Trying `--legacy-peer-deps` now to see if it works

**Comment by thegnuu** [comment]
Hi guys! I am currently on vacation and I don't really have the possibility to test my changes on real devices. If anyone of you can test the branch https://github.com/capacitor-community/barcode-scanner/tree/capacitor-v4 I can create a release this week, otherwise it will be sometimes next week unfortunately...

**Comment by hauserkristof** [comment]
@ssj7 try to install the capacitor 4 branch version with
```
npm install --save https://github.com/capacitor-community/barcode-scanner/tree/capacitor-v4
```

It is working until they do not merge the changes.

Also, it worths a look on the PR #142 the ```self``` keyword is missing from the code yet.

**Comment by thegnuu** [comment]
I just released v3, thanks to everyone that helped on this issue!
