### ISSUE TITLE
UI broken on Android since upgrade to Capacitor 4

### ISSUE THREAD

**Issue by heinerlamprecht** [capacitor-community/barcode-scanner#147]
Since upgrade to Capacitor 4 and version 3 of this plugin, the previous custom UI does not show up again on Android.  The complete WebView is hidden (not even accessible through the Chrome debugger).  Besides, the scanner now shows some information about the scanned code already while scanning.

On iOS, the behaviour is the same as before the upgrade.

Tested on Galaxy Tab A8 with Android 11

**Comment by thegnuu** [comment]
Unfortunately I am not able to reproduce this issue... 
Can you share a repo where I can reproduce your problem?

Without an implementation to debug it won't be possible for me to help you....

**Comment by Squix** [comment]
As for me, splashscreen (probably the new Android 12 one) is showing between the scanner UI and the camera view.
Scanning is working (when a barcode is in front of the camera), even if nothing is visible.

**Comment by thegnuu** [comment]
You should be able to remove the splashscreen with some ionic plugins, have you already tested this?

**Comment by thegnuu** [comment]
Please check out this: https://github.com/capacitor-community/barcode-scanner#ionic-css-variables

If you still have issues, feel free to reopen this issue :)

**Comment by Squix** [comment]
I couldn't remove the new splashscreen with the splashscreen capacitor plugin. But I was able to revert to the old splashscreen by edtiting the _android/app/src/main/res/values/styles.xml_ file, doing the contrary described here : https://capacitorjs.com/docs/updating/4-0#optional-use-the-new-android-12-splash-screen-api
