### ISSUE TITLE
The UI doesn't show up in Android 8.1 (light mode, Capacitor 6, Ionic 4, Angular 14, WebView 70)

### ISSUE THREAD

**Issue by salazarbarrera** [capacitor-community/barcode-scanner#156]
**Describe the bug**
I can't [find the scanner in the DOM](https://github.com/capacitor-community/barcode-scanner#i-do-not-find-the-scanner-in-the-dom). I followed the advice to manually [hide certain objects](https://github.com/capacitor-community/barcode-scanner/issues/26#issuecomment-808943754) as it was suggested by other users but it didn't work. I also tried to start BarcodeScanner from `app.component.ts`, unsuccessfully. 

You can see an example project [here](https://github.com/salazarbarrera/barcodeIonicTest).

**To Reproduce**

1. Clone the example repo above ([this one](https://github.com/salazarbarrera/barcodeIonicTest))
2. Connect the device, execute `$ ionic cap run android` and select the target device. Alternatively you can compile, install and run it with Android Studio after executing `$ ionic cap add android`. 
4. After seeing the splash screen, you will see the "...Scanner Interface" div I added below the body div, but no scanner will appear, neither visually nor in the DOM.

**Expected behavior**
At least the BarcodeScanner should appear in the DOM.

**Version**
v3.0.0

**Smartphone**

- Device: PAX Android POS
- OS: Android 8.1
- Browser: WebView 70.0.3538.110
- Angular: 14.0.0
- Ionic: 6.20.1
- "@capacitor/core": "4.1.0
- "@capacitor/app": "4.0.1"

**Comment by salazarbarrera** [comment]
The same code was tested in a vanilla Android 11 with WebView 104.0.5112.97.

Same results.

**Comment by thegnuu** [comment]
@salazarbarrera you are not requesting permission the the camera.
Without camera permission the plugin will never be able to display something ;)

Check the docs for permission, the easiest way for testing is to add `await BarcodeScanner.checkPermission({ force: true });` before calling `await BarcodeScanner.startScan()`, but you should implement better checks based on the state of course :)

After adding the check it worked without any issues on my device.

**Comment by salazarbarrera** [comment]
I'll open another issue about that when I modify the code after work. About this matter, the problem is solved.
