### ISSUE TITLE
startScanning returns -1 

### ISSUE THREAD

**Issue by 1andonlyziz** [capacitor-community/barcode-scanner#158]
When using startScanning() function, -1 will be returned for each result
But it logs well on android studio when a barcode is detected 

I'm using version 3.0.0

<img width="1155" alt="CleanShot 2022-09-15 at 10 00 19@2x" src="https://user-images.githubusercontent.com/73785385/190336506-adfe2f60-e1cc-4177-8f06-1d181908d7f1.png">

**Comment by thegnuu** [comment]
Can you provide a repo to reproduce this issue?

**Comment by 1andonlyziz** [comment]
@thegnuu sorry it turns out I'm not using the callback properly ^_^"

**Comment by thegnuu** [comment]
Yep, this might result into some errors ;)

Glad you found the solution :)
