### ISSUE TITLE
No way to cancel barcode scan

### ISSUE THREAD

**Issue by brian-g** [capacitor-community/barcode-scanner#159]
**Describe the bug**
In the current implementation, there is no way to cancel the scan of the barcode on iOS (not sure if this affects Android). This is an issue because a user may inadvertently initiate a barcode scan and then not have a barcode to scan that would dismiss the interface. 

**Expected behavior**
I expect there is a way to cancel the operation. 

**Version**
2.1.1

**Desktop (please complete the following information):**

- OS: iOS

**Smartphone (please complete the following information):**

- Device: iPhone 13 Pro
- OS: iOS 16
- Browser: Safari
- Version: Latest

**Comment by thegnuu** [comment]
There is a `stopScan` function which will stop the current scanning process...

**Comment by CT-SmartWaterPlanet** [comment]
The stopScan btn needs to be configured, which is unclear how to do it.

On the other hand, when I cancel the scan or finish it, the camera is still active as in the background. how can i solve that?
