### ISSUE TITLE
unable to use in android

### ISSUE THREAD

**Issue by Darkmagister** [capacitor-community/barcode-scanner#165]
**Describe the bug**
i'm trying this plugin to test the barcode functionality, i have installed following the readme but i get 
```
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(HomePageModule)[BarcodeScanner -> BarcodeScanner -> BarcodeScanner -> BarcodeScanner]: 
      NullInjectorError: No provider for BarcodeScanner!
    NullInjectorError: R3InjectorError(HomePageModule)[BarcodeScanner -> BarcodeScanner -> BarcodeScanner -> BarcodeScanner]: 
      NullInjectorError: No provider for BarcodeScanner!
```
in android studio

**To Reproduce**

i'm starting from a blank project ionic with angular, installed the plugin, edited the AndroidManifest.xml file in the home page of the project i just added a button that should call a function with the example function from the readme, after installing the app on the device after the start, the app doesn't show the button and i get that error

**Expected behavior**
showing the app and scan

**Desktop (please complete the following information):**

- OS: Linux
- Browser firefox
- Version 106

**Smartphone (please complete the following information):**

- Device: Xiaomi mi mix 2s
- OS: miui 12 - android 10

here you can see the test app:
https://github.com/Darkmagister/testbarcode

**Comment by thegnuu** [comment]
I will have a look at this as soon as possible, unfortunately I am really busy at the moment...

**Comment by thegnuu** [comment]
@Darkmagister sorry it took me so long to respond!

I was able to start your project without any issues, the only thing that prevented the scanner from being visible is the `--ion-background-color` css variable which need to be set to `transparent`. Otherwise I had no issues with your project on my Huawei test device.

Feel free to reopen this issue if the problem still exists!
