### ISSUE TITLE
Dangling promise when stopping scan

### ISSUE THREAD

**Issue by mauriceackel** [capacitor-community/barcode-scanner#17]
**Describe the bug**
When a scan is active (i.e. `const result = await BarcodeScanner.startScan();`) and the scan gets stopped somewhere else (i.e. `BarcodeScanner.stopScan();`). The original promise is neither resolved nor rejected.

**To Reproduce**

1. Start a scan and await the result.
2. Stop the scan from somewhere else.
3. Code after the `await` will not be executed and if it is in a try-catch block, the catch does not fire

**Expected behavior**
The 'scan promise' should either be resolved (i.e. with `hasContent` being  `false`) or it should be rejected. Personally, I would prefer it to be resolved without content.

**Version**
v1.1.1

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: iPhone8 Plus
- OS: iOS 14.4
- Capacitor: 2.4.6

**Comment by mauriceackel** [comment]
I'm a noob when it comes to capacitor plugins but I checked the code and perhaps it is just sufficient to check if the `savedCall` exists inside the `stopScan` function and if so, resolve it?!

**Comment by tafelnl** [comment]
I think this is a legit use case. However, your solution would require a major version bump, since it is a breaking change. But we could maybe introduce an option to `stopScan` to enable this. Such as a `resolveScan` boolean for example. Agree?

**Comment by tafelnl** [comment]
Also I think rejecting it would make more sense, since it did not recognize a barcode or something.

**Comment by mauriceackel** [comment]
Yes, I think an additional option would be totally fine :)
Regarding rejecting or resolving: I guess it comes down to your design decision. I just thought that due to the fact that there is this "hasContent" property, the Start scan was supposed to also not return any content...

**Comment by tafelnl** [comment]
Yes, I think that would be the right way to go about this. I will implement this together with #11 in the next release. ETA: 22nd of feb.

**Comment by mauriceackel** [comment]
Nice, I appreciate it! 🚀

**Comment by tafelnl** [comment]
Just a quick update. I did not forget about this issue. But I have been really busy lately. If anyone could join in to give this a shot, it would be very much appreciated. Otherwise I will look into this in a few weeks.

**Comment by mauriceackel** [comment]
Hi @tafelnl, as I said I have no experience with Capacitor Plugins but based on the current code I came up with the following: 192851f1196a69fa2af962e1afcedf4cf38d8d78.

I'm not sure whether this will break things as it might be necessary to make the `options` parameter optional in the type definition. I have also not tested this in any way but maybe it is a fair starting point for an implementation.

**Comment by tafelnl** [comment]
Closed by #51 (874466cdf35334319290f3c49fe3ae79e20b368f)
