### ISSUE TITLE
Anyway to border around qrcode

### ISSUE THREAD

**Issue by huuhait** [capacitor-community/barcode-scanner#176]

**Comment by huuhait** [comment]
> With the current implementation this is not possible, I am working on a new version based on `ml-kit` that will allow this.

Hope it will done very soon

**Comment by thegnuu** [comment]
It should, I am doing my best to release it asap, unfortunately I am kinda busy with other projects at the moment...

**Comment by 5ynatra** [comment]
@thegnuu I presume it's still a WiP? is a branch available for it that I could potentially assist with?

**Comment by JanMisker** [comment]
> @thegnuu I presume it's still a WiP? is a branch available for it that I could potentially assist with?

Yeah the ml-kit branch. There are some issues marked with [ML-Kit] that could be starting points to contribute.

**Comment by thegnuu** [comment]
@5ynatra I just release `v5.0.0-beta.1` based on the `ml-kit` branch. My current problem is to map the points returned by ml-kit to the matching pixel values in the webview. If we can achieve this, it should be quite easy to implement the outlines yourself... If you would have time to look at this and maybe come up with a working solution this would be awesome :)

**Comment by thegnuu** [comment]
See #217

**Comment by thegnuu** [comment]
This is as well related to this issue #205.
I will close this one here to remove "duplicates"
