### ISSUE TITLE
Barcode Scanner not open

### ISSUE THREAD

**Issue by mobiliseapplabllp** [capacitor-community/barcode-scanner#178]
Barcode Scanner Not open & not show any error

Ionic & Capacitor Version

Ionic:

   Ionic CLI                     : 6.19.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.8
   @angular-devkit/build-angular : 15.0.1
   @angular-devkit/schematics    : 15.0.1
   @angular/cli                  : 15.0.1
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 4.5.0
   @capacitor/android : 4.5.0
   @capacitor/core    : 4.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   NodeJS : v16.16.0 (/Users/apple/.nvm/versions/node/v16.16.0/bin/node)
   npm    : 8.11.0
   OS     : macOS Monterey

** Barcode plugin version
"@capacitor-community/barcode-scanner": "^3.0.1",

** Testing in two android mobile
1) Redmi 9 prime (android 10)
2)Samsung f23 5g(android 12)

**Comment by thegnuu** [comment]
Have you checked out this?

https://github.com/capacitor-community/barcode-scanner#opacity-of-the-webview

**Comment by thegnuu** [comment]
You might need to set other elements transparent depending on your setup...

**Comment by thegnuu** [comment]
I will close this due to inactivity.
