### ISSUE TITLE
Append camera to <video /> element

### ISSUE THREAD

**Issue by huuhait** [capacitor-community/barcode-scanner#180]
Hi i think we should append camera into `<video />` element
because most off application using page transitions
it's better if can be
Thanks

**Comment by thegnuu** [comment]
As of now this is not possible as far as I know. The IPC communication between the native code and the DOM renderer needs to be serializable, which is not possible with some sort of streams. The only way would be to serialize each frame, send it to the DOM and somehow display this as some sort of "video", which would result in a horrible performance. There would not be a way to properly handle the position of the `video` element and verify, that only codes in this area are scanned, at least not with a lot of overhead for the devs that implement the plugin.
