### ISSUE TITLE
Camera appears and disappears...

### ISSUE THREAD

**Issue by marcelo-jrkiko** [capacitor-community/barcode-scanner#181]
**Describe the bug**
When i trigger the startScan, the camera view appears, but soon after its disappears and all webview is reloaded.. 

**To Reproduce**
Just run the startScan

 document.querySelector('body')!.classList.add('scanner-active');
      await BarcodeScanner.checkPermission({force: true});

    //  await BarcodeScanner.hideBackground();
      
      const res = await BarcodeScanner.startScan();

      if(res.hasContent) {
        this.codigoDigitado = res.content!;        
        this.onAdicionarProduto();
      }

      document.querySelector('body')!.classList.remove('scanner-active');

**Screenshots**
[Video of the issue](https://preview.redd.it/qqvxdjzdli5a1.gif?format=mp4&s=9af2df68703db5159238ca6344fea9267f50e6eb)

**Version**
v3.0.0

- OS: Android 11
- Runnig In IONIC with Capacitor 4.3.0

**Comment by thegnuu** [comment]
I am not able to reproduce it with my available test devices, it might be related to the camera of your device or something.
Unfortunately I am not really able to help you if I am not able to reproduce the behaviour on my end...

For me it looks like the camera in the video starts properly, but it seems to have issues adapting to the current environment lighting, since the image is never completely faded out, only the image brightness changes.

Have you tested it with another device?

**Comment by marcelo-jrkiko** [comment]
Addendum

 Include preventDefault and stopPropagation in the Button Click Event code:

```
 e.preventDefault();
      e.stopPropagation();

      await BarcodeScanner.checkPermission({ force: true });
      
      await BarcodeScanner.hideBackground();
      document.querySelector('body')!.classList.add('scanner-active');

      const res = await BarcodeScanner.startScan();

      if (res.hasContent) {
        this.codigoDigitado = res.content!
        this.onAdicionarProduto();
      }

      document.querySelector('body')!.classList.remove('scanner-active');
```
Now the ionic doesnt reload, however the camera does not appear...
Console log:

```
VM4:243 native BarcodeScanner.checkPermission (#99121081)
VM4:250 ObjectcallbackId: "99121081"methodName: "checkPermission"options: {force: true}pluginId: "BarcodeScanner"[[Prototype]]: Object
VM4:217 result BarcodeScanner.checkPermission (#99121081)
VM4:228 Objectgranted: true[[Prototype]]: Object
VM4:243 native BarcodeScanner.hideBackground (#99121082)
VM4:250 ObjectcallbackId: "99121082"methodName: "hideBackground"options: {}pluginId: "BarcodeScanner"[[Prototype]]: Object
VM4:217 result BarcodeScanner.hideBackground (#99121082)
VM4:228 undefined
VM4:243 native BarcodeScanner.startScan (#99121083)
VM4:250 ObjectcallbackId: "99121083"methodName: "startScan"options: {}pluginId: "BarcodeScanner"[[Prototype]]: Object

**Comment by thegnuu** [comment]
Thank you for providing additional information. But as I said, I am not able to reproduce it on my end which makes it hard to help you in that case.

The only way I am able to check and debug it is with an example repo which helps me to reproduce your issue, if I have code that behaves in this way I might be able to reproduce it with one of my devices and help you find a solution. 

My test repository based on Ionic/Angular works as expected.

**Comment by marcelo-jrkiko** [comment]
Well I solved it, I don't understand exactly where the problem is.
The code was being triggered through the 'click' of a button that was inside the view, inside a IonContent element.
As a test, I created a new view, without the IonContent. In this view in the "mounted" method , i call after a certain time for the "startScan". After scanning, I save the data and send a 'router.push' to the previous view. So I managed to create a mechanism to use the scanner. 

And it works.

```
<template>

</template>


<script lang="ts">
import { defineComponent } from 'vue';
import { BarcodeScanner } from '@capacitor-community/barcode-scanner';
import { BarcodeScannerRuntime } from '@/core/BarcodeScanner';
import { useRouter } from 'vue-router';

export default defineComponent({
    name: 'BarcodeScanner',
    setup() {
        const router = useRouter();
        return { router };
    },
    mounted() {
        setTimeout(() => {
            this.doScan().then(() => {
                this.router.push(BarcodeScannerRuntime.LastPage!);
            });
        }, 200);
    },
    methods: {
        async doScan() {
            await BarcodeScanner.checkPermission({ force: true });

            await BarcodeScanner.hideBackground();
            document.querySelector('body')!.classList.add('scanner-active');

            const res = await BarcodeScanner.startScan();
            BarcodeScannerRuntime.HasScanned = res.hasContent;
            BarcodeScannerRuntime.Data = res.content;

            document.querySelector('body')!.classList.remove('scanner-active');
        },
    }
});
</script>
```
Now I'm curious to know what component of the Ionic was causing problems...

**Comment by thegnuu** [comment]
Glad you found a solution for your issue. This seems indeed weird, my setup with the ionContent is more or less the same, but I am using angular and not vue.

Sorry I was not able to help you, I have no idea what might cause an issue like this.
