### ISSUE TITLE
I know the issue is already closed, but I would like to add some notes.

### ISSUE THREAD

**Issue by JalzDeLezZ** [capacitor-community/barcode-scanner#191]
I know the issue is already closed, but I would like to add some notes.
I got the same error "plugin is not implemented on android".
The reason in my case for this was the used angular "monorepo" project structure. 

Capacitor checks package.json for plugins. 
Because my ionic project within the monorepo under projects/my-app had a package.json, capacitor used this to check for plugins to include under android/capacitor.settings.gradle.
Dependencies in monorepos are installed in the root of the repo, the capacitor plugins (e.g BarcodeScanner) were listed in the root package.json instead of the apps package.json.

So if you run into a similiar problem, list the npm package for the capacitor plugin within your apps package.json "dependencies".

_Originally posted by @oldjazjef in https://github.com/capacitor-community/barcode-scanner/issues/60#issuecomment-962026479_

**Comment by tafelnl** [comment]
This is not an issue with this library as per explanation in the comment and related comments and issue.
