### ISSUE TITLE
Android build is failing with latest version of the barcode scanner

### ISSUE THREAD

**Issue by Raghavaraju-K** [capacitor-community/barcode-scanner#192]
**Describe the bug**

**To Reproduce**

1. Add the plugin in json file
2. build the code  and run thhe project in the device
4. android build throws excepotions
<img width="330" alt="Screenshot 2023-02-06 at 12 46 46 PM" src="https://user-images.githubusercontent.com/64583582/216908031-dc5e6885-130d-4439-998f-7c4fdf5d60f0.png">

**Expected behavior**
plugin intallation shpuld work for android

**Screenshots**

**Version**
[e.g. v1.0.0]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thegnuu** [comment]
The error you are providing is thrown in a Capacitor class and is not caused by this plugin.
You must first ensure your project will work without the plugin. If there are some problems related to the plugin I will do my best to help, but in this case, I am unfortunately not able to help you
