### ISSUE TITLE
Change prepare hook to prepublishOnly 

### ISSUE THREAD

**Issue by malua** [capacitor-community/barcode-scanner#200]
Hey there!

Thank you for maintaining this plugin!

I wanted to ask if it would be possible to use the `prepublishOnly` hook instead of `prepare` for the build script.

I have created an Nx monorepo with our capacitor whitelabel apps and to make dependency management easier I have adpoted this system:
https://github.com/nxext/nx-extensions/discussions/794#discussioncomment-5218635

And the problem is that the `prepare` hook is executed when installing the the plugins to the inner `package.json` with 
`npm install file:../../node_modules/@capacitor-community/barcode-scanner`.

So I wanted to ask if it was possible to use the `prepublishOnly` hook instead?

```diff
diff --git a/node_modules/@capacitor-community/barcode-scanner/package.json b/node_modules/@capacitor-community/barcode-scanner/package.json
index 3989f9c..5033efe 100644
--- a/node_modules/@capacitor-community/barcode-scanner/package.json
+++ b/node_modules/@capacitor-community/barcode-scanner/package.json
@@ -36,7 +36,7 @@
     "build": "npm run clean && tsc && rollup -c rollup.config.js",
     "clean": "rimraf ./dist",
     "watch": "tsc --watch",
-    "prepare": "npm run build",
+    "prepublishOnly": "npm run build",
     "verify": "npm run verify:ios && npm run verify:android && npm run verify:web",
     "verify:ios": "cd ios && pod install && xcodebuild -workspace Plugin.xcworkspace -scheme Plugin -destination \"platform=iOS Simulator,name=iPhone 12\" && cd ..",
     "verify:android": "cd android && ./gradlew clean build test && cd ..",
```

**Comment by thegnuu** [comment]
Don't see an issue in this, I will create a release today :)
