### ISSUE TITLE
Add WIFI from QR code

### ISSUE THREAD

**Issue by tpharaoh** [capacitor-community/barcode-scanner#21]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
when you scan a QR code with wifi data with native camera it offers to connect to wifi
WIFI:T:WPA;S:myHome;P:12345678;H:false;

**Comment by tafelnl** [comment]
In my honest opinion this is outside the scope of this package. If someone would like to connect to a WIFI spot through a QRcode they would use their native QR scanner. However, if you want to add such capability to your app, you should implement that yourself. On Android you could start by looking at this SO issue: https://stackoverflow.com/questions/8818290/how-do-i-connect-to-a-specific-wi-fi-network-in-android-programmatically

**Comment by tafelnl** [comment]
However, I will keep track of this and similar issues. If it receives enough attention I will consider implementing it. And of course you could always submit a PR yourself.

**Comment by tpharaoh** [comment]
On further research, I think I agree with you, it doesn't belong in your
package, I should use something like WifiWizard2.

I am probably not qualified to do the native side here. WifiWizard2 is not
being updated anymore. My company offered to pay him to update it... but no
response... oh well. I'll think I will have to solve this another way... in
all cases, thanks for your prompt response, and valuable feedback.

**Comment by mdniamul4455** [comment]
#211

**Comment by mdniamul4455** [comment]
#21
