### ISSUE TITLE
[ML-Kit] Fix Android permission handling

### ISSUE THREAD

**Issue by thegnuu** [capacitor-community/barcode-scanner#213]
There are some issues with the current permission handling, the easiest way would be to copy the permission system from `@capacitor/camera` which resolved all the issues already.

**Comment by Jopie01** [comment]
I walked into this as well. The dialog for asking permissions didn't show up.

Instead of using the default
```await BarcodeScanner.checkPermission();```
I used 
```await BarcodeScanner.requestPermissions();```
which was working and the dialog for asking permissions was shown.

**Comment by thegnuu** [comment]
@Jopie01 yes, this is by design ;) I already started the implementation and this is the behaviour `@capacitor/camera` has, IMHO it makes sense to differentiate between checking and requesting the permission in this case. It will need to be documented of course :)

But there should be a fallback that will request the permission every time if you want to start a scan and the permission is not asked yet I think. This way you have the option to implement your own checks, but they will be enforced if not asked. This is the default behaviour on iOS as well as far as I know.

**Comment by thegnuu** [comment]
This should work, maybe it is not fully tested in each use case, but in general it works :)
