### ISSUE TITLE
Flas light is off automatically once scanning is successful

### ISSUE THREAD

**Issue by anusha-kaparapu** [capacitor-community/barcode-scanner#214]
Flash light is turned off automatically once scanning is successful. 

 @thegnuu   **Is there any way or solution to keep the flash light on while continuing to scan?**

**Comment by thegnuu** [comment]
Weird, on my device the torch keeps running.

Are you working on Android or iOS?

**Comment by anusha-kaparapu** [comment]
@thegnuu I tested in both the devices android and iOS
**The following methods i have return to scan the barcode.** 
startScanner() {
       
            this.scanActive = true;
            await BarcodeScanner.hideBackground();
            document.body.classList.add('scanner-active');
            const result = await BarcodeScanner.startScan();
            if (result.hasContent) {
                this.serialNum = result.content;
                this.enableTorchState();
                // API call for storing the result
                if (result.content) {
                    await this.getSerialNumberFromSearch();
                }
            } else{
                this.continuosScan();
            }
      
    }
async enableTorchState(){
        await BarcodeScanner.enableTorch();
    }
continuosScan() {
                this.startScanner().catch(() => {});
    }

please let me know anything i missed here.

**Comment by thegnuu** [comment]
Would it be possible for you to create a repo to reproduce the issue?

It's kinda hard to reproduce it with just some snippets ;)

**Comment by JanMisker** [comment]
You are repeatedly calling `startScan()`, which will re-initialize the camera every time. If you want continuous scanning you should check out the `startScanning()` method, which gets a callback that is called whenever a new code is found.

The `startScanning(options, callback)` method is not documented unfortunately, but basically works like this:
```
BarcodeScanner.startScanning({}, (result) => {
    // do something with the results like this.getSerialNumberFromSearch()
});
```
If you want to pause after getting a result you can call `pauseScanning()` and `resumeScanning()`.

**Comment by anusha-kaparapu** [comment]
Hi @JanMisker and @thegnuu flash light is working now using of startScanning(options, callback), Thank you very much :)
