### ISSUE TITLE
Is it possible to render in a div with width and something specific?

### ISSUE THREAD

**Issue by danielchirinos** [capacitor-community/barcode-scanner#218]
hello everyone,

when i run the plugin it works correctly, but it appears on the whole screen, is it possible to make it appear in a div with defined width and height?

I tried to add the entire plugin within a component in ionic and I gave said component a fixed width and height, but it still opens the scan on the entire screen

Thanks in advance

**Comment by JanMisker** [comment]
No. The camera view is not embedded inside the DOM / component tree. It is rendered behind the webview. What you can do is place non-transparent content in your component that blocks the view partially, creating a similar effect. But do note that the qr recognition happens in the entire view, also in the blocked regions, and you can not specify a subregion.
