### ISSUE TITLE
The scanner view does not show up on ios and android

### ISSUE THREAD

**Issue by srwebdev5515** [capacitor-community/barcode-scanner#219]
**Describe the bug**

The following code does not show up on ios and android devices.
```
<body>
  <!-- ... -->
  <div style="position: absolute; left: 0px; top: -2px; height: 1px; overflow: hidden; visibility: hidden; width: 1px;">
    <span
      style="position: absolute; font-size: 300px; width: auto; height: auto; margin: 0px; padding: 0px; font-family: Roboto, Arial, sans-serif;"
      >BESbswy</span
    >
  </div>
  <!-- ... -->
</body>
```

When I run the project with "ng serve" and open it on the browser, it is working correctly and I am able to scan the code.
But when I run the project on android or ios devices and inspect it, that scanner code does not show up in HTML.

**Screenshots**
![image](https://user-images.githubusercontent.com/28256307/230583086-727c3a32-616e-4d54-aba0-20698bdfd8e6.png)
![image](https://user-images.githubusercontent.com/28256307/230583233-c50f34ad-1bd9-4a72-b7ae-48c5180a04bb.png)

**Version**
"@ionic/angular": "^6.1.9",
"@capacitor/android": "^4.7.3",
"@capacitor/app": "4.1.1",
"@capacitor/core": "4.7.0",
"@capacitor-community/barcode-scanner": "^3.0.3",

**Comment by thegnuu** [comment]
Ionic will behave differently on different devices and "display modes" (dark or light mode).

There are classes and variables added to different DOM elements, you need to verify that your complete tree is transparent, only looking at the body will not be enough in this case.

**Comment by srwebdev5515** [comment]
> Ionic will behave differently on different devices and "display modes" (dark or light mode).
> 
> There are classes and variables added to different DOM elements, you need to verify that your complete tree is transparent, only looking at the body will not be enough in this case.

Thank you for your reply, @thegnuu .
But it's not related to transparent style. I can't find HTML code that this plugin adds to DOM at all.

**Comment by thegnuu** [comment]
This is expected as well. Only the web implementation will add HTML video elements :)

On iOS/Android the camera view is rendered behind the webview and will not be visible in the DOM.

**Comment by srwebdev5515** [comment]
Oh, I got it. How can I verify that it's working fine but just a transparent issue?

**Comment by thegnuu** [comment]
If you are not getting any errors in the console you should be fine.
The easiest way is to scan a code and check the logs if you receive something.

If this works, which it usually does if we receive an issue like this, you can check the readme and some other issues regarding the transparency "problems", there are a few different solutions for different setups. If it still not works it is most likely a permission issue.

**Comment by srwebdev5515** [comment]
Oh, right. I just tried to make every elements of DOM to be transparent and I can see the scanner now.
Sorry about the confusing and thank you for your help!

**Comment by thegnuu** [comment]
No worries, you're welcome :)

**Comment by ThomasRambaud** [comment]
For Ionic this is what I did:

body.scanner-active #root {
    opacity: 0;
}

Making background: transparent is not enough.
