### ISSUE TITLE
Warning: (ios) discoverCaptureDevices()' is deprecated

### ISSUE THREAD

**Issue by rbalet** [capacitor-community/barcode-scanner#220]
**Describe the bug**
While compiling I do get the following warning

```
'discoverCaptureDevices()' is deprecated: New Xcode? Check if `AVCaptureDevice.DeviceType` has new types and add them accordingly.
            let availableVideoDevices =  discoverCaptureDevices()
```

**Version**
v3.0.3

**Expected behavior**
No warnings :)

**Comment by thegnuu** [comment]
@rbalet this should not be an issue :) I am aware of the deprecation and this is already fixed in an upcoming version. You should be able to use the plugin without any issue!

**Comment by rbalet** [comment]
@thegnuu nice, it was just to be sure you were aware of it ;)
