### ISSUE TITLE
Barcode is not scanning

### ISSUE THREAD

**Issue by kumarjitendra-epic** [capacitor-community/barcode-scanner#222]
Hi,
We are using capacitor plugin for barcode scanning. We are able to scan qrcodes but barcodes are not getting scanned. QRcodes are working all OK. Any hint will be really appreciated. Thanks in advance

scanIT() {
  async checkPermission() {
    return new Promise(async (resolve, reject) => {
      const status = await BarcodeScanner.checkPermission({ force: true });
      if (status.granted) {
        resolve(true);
      } else if (status.denied) {
        alert('Give access to camera');
      } else {
        resolve(false);
      }
    });
  }
async stopScan(){
  BarcodeScanner.stopScan();
}
async prepareScan(){
  await BarcodeScanner.prepare({targetedFormats:['EAN_13']})
}
  async onScan() {
    await this.checkPermission();
    await BarcodeScanner.hideBackground();
    document.querySelector('body').classList.add('scanner-active');
    const result = await BarcodeScanner.startScan({cameraDirection: "back" });
    console.log('After Start Scan ' + result.content);
    await BarcodeScanner.showBackground  ();
    document.querySelector('body').classList.remove('scanner-active');
  }

**Comment by kumarjitendra-epic** [comment]
hi,
thanks for the prompt reply. Do you think using ml-kit may work, I can try integrating this(not sure how far can I go). Any leads from you?

**Comment by JanMisker** [comment]
Hi @kumarjitendra-epic you are more than welcome to make your own fork and clone it to your local machine. Then you can checkout the branch and test by installing the plugin locally, see the Capacitor guide for more info how to do that. https://capacitorjs.com/docs/plugins/workflow#local-testing

**Comment by levarberry** [comment]
I would assume for 1D barcodse then we'd need to use the phonegap plugin until there is a better capacitor version?

**Comment by JanMisker** [comment]
@levarberry I think the ml-kit branch is already good for use, next week we are releasing an app that uses that branch. Workflow is to clone this repository, switch to the ml-kit branch, install the plugin locally (see Capacitor docs how to do that). 

Do note that the API changed.

**Comment by thegnuu** [comment]
@kumarjitendra-epic unfortunately not, due to unforeseen issues in my own project I had no time this week.

Hopefully I can find time next week to finish things up.

**Comment by kumarjitendra-epic** [comment]
Also, I am trying to use cameradirection as back, it works fine when run in browser but as soon as I use the apk on mobile, it stops working

**Comment by JanMisker** [comment]
> @JanMisker , by any chance the new plugin has been released that you are discussing about?

you'd have to clone this repository locally and switch to the ml-kit branch.
