### ISSUE TITLE
Issue with specific phones Samsung Ultra S21 and S22

### ISSUE THREAD

**Issue by gentlyawesome** [capacitor-community/barcode-scanner#223]
I have already deployed a sample apk that uses the barcode scanner. The plugin is already tested in Android and iOS but there are specific devices that do not trigger the QR Code Camera: Samsung Ultra S21 and S22. Is there an update needed?

**Comment by kumarjitendra-epic** [comment]
@gentlyawesome , can you please share the code for the barcode scanner that you have written. I tried using as specified but it doesn't scans the bar code, where QR code is scanned perfectly. Help would be really appreciated.

**Comment by thegnuu** [comment]
@gentlyawesome you might be able to get better results with the new pre-release `v5.0.0-beta.1`. 

Unfortunately I am still not able to test it with one of those devices, so I will close the issue for now.

@kumarjitendra-epic If you still have problems feel free to open a new issue.

**Comment by Waterdhavian** [comment]
I have tested version 3, version 4 and the beta version 5 on 2 samsung android devices, both of them worked like 2 months ago. Nothing was changed in my app (as in version of this plugin or other packages) but the phones did receive an update from Samsung with updates. And last week i needed to test it again and it stopped working on both of my devices. Before version 3 worked. Now version 3, 4 and the beta 5 don't work. Pretty sure this is because of something that Samsung changed. 

The plugin does not give an error in the console but the DOM element that holds the video feed is not created / not showing. We already had some contact about this @thegnuu about the beta version where it did give an error in Android Studio. I have checked but version 3 and 4 don't give me an error but also still not working.

Hoping someone in the community here with a Samsung can help resolve this, i am open to assist and help where i can.

**Comment by nvahalik** [comment]
We have an issue similar to this... it's an S21.

We also use the https://github.com/capacitor-community/camera-preview module. When we navigate to a page that uses that module, it prompts for permission and then we can use the barcode scanner.

**Comment by nvahalik** [comment]
Honestly, it almost looks like the code for handling the permissions check on Android is just... missing.

We seem to have gotten this working by changing this:

    BarcodeScanner.checkPermission()
        .then((r) => {
          // scan all the things
        })

to this:

    BarcodeScanner.checkPermission()
        .then((r) => {
          // Only continue if we have granted permissions.
          if (r.granted) {
            return r;
          }
          return BarcodeScanner.checkPermission({force: true});
        }).then(() => {

**Comment by gentlyawesome** [comment]
> @gentlyawesome you might be able to get better results with the new pre-release `v5.0.0-beta.1`.
> 
> Unfortunately I am still not able to test it with one of those devices, so I will close the issue for now.
> 
> @kumarjitendra-epic If you still have problems feel free to open a new issue.

I'll try this one out.

**Comment by gentlyawesome** [comment]
> Honestly, it almost looks like the code for handling the permissions check on Android is just... missing.
> 
> We seem to have gotten this working by changing this:
> 
> ```
> BarcodeScanner.checkPermission()
>     .then((r) => {
>       // scan all the things
>     })
> ```
> 
> to this:
> 
> ```
> BarcodeScanner.checkPermission()
>     .then((r) => {
>       // Only continue if we have granted permissions.
>       if (r.granted) {
>         return r;
>       }
>       return BarcodeScanner.checkPermission({force: true});
>     }).then(() => {
> ```

I tried to use this but still didn't work.

**Comment by gentlyawesome** [comment]
> We have an issue similar to this... it's an S21.
> 
> We also use the https://github.com/capacitor-community/camera-preview module. When we navigate to a page that uses that module, it prompts for permission and then we can use the barcode scanner.

Did this work on your end?

camera-preview will handle permission and then use barcode scanner plugin?

**Comment by gentlyawesome** [comment]
> @gentlyawesome you might be able to get better results with the new pre-release `v5.0.0-beta.1`.
> 
> Unfortunately I am still not able to test it with one of those devices, so I will close the issue for now.
> 
> @kumarjitendra-epic If you still have problems feel free to open a new issue.

I have used the latest https://github.com/capawesome-team/capacitor-mlkit/tree/main/packages/barcode-scanning

which was a branch and worked in the Samsung phones. Thank you. :)
