### ISSUE TITLE
The Web/App content is on top of the QR Scanner view

### ISSUE THREAD

**Issue by GiustiRo** [capacitor-community/barcode-scanner#227]
**Describe the bug**
When I successfully open the scanner, all html elements still on top of the camera instance.

**To Reproduce**

Installed the plugin following your instructions.
Open the Scanner Ok.
HTML elements like button, p, etc are showing on top of the scanner view (camera).

**Expected behavior**
The app Should hide all the content among setting transparency.

**Screenshots**
<img src="https://user-images.githubusercontent.com/39607414/233854332-aac6a900-e2af-4f57-b9f0-d7d8ad5dea7c.jpg" height="400" alt="QR and HTML overlay">

**Version**
3.0.3

**Smartphone (please complete the following information):**
- Device: Xiaomi Redmi Note 8
- OS: Android 9 pkq1.19 / MIUI Global 11.0.12

**Additional context**
Ionic 'Blank App' Template.

**Comment by thegnuu** [comment]
This is by design an cannot/will not be changed. Tou need to ensure yourself that the content you need is visible and the one you don't want is hiddden

**Comment by GiustiRo** [comment]
Oh okey I get the point! Thanks for your anwser
