### ISSUE TITLE
support for multiple scan 

### ISSUE THREAD

**Issue by MahmoudMm** [capacitor-community/barcode-scanner#230]
I saw these two question 
[ Add support for multiple scan (multiple barcode at once) #168 ](https://github.com/capacitor-community/barcode-scanner/issues/168)
[feat: add support for continuous scanning (multiple barcodes in one go) #43](https://github.com/capacitor-community/barcode-scanner/issues/43)

I wonder will this feature will be supported soon!?

**Comment by thegnuu** [comment]
This is already supported :) Unfortunately, the docs are not really up2date...

https://github.com/capacitor-community/barcode-scanner/blob/4d2238157608687ca8b101a5b452b60d7886d676/src/definitions.ts#L7

The docs will be updated with the next major release anyways :)

**Comment by MahmoudMm** [comment]
Oh, Thank you for the answere, Hope you keep the good work 🙏🙏🙏🙏
