### ISSUE TITLE
"BarcodeScanner" plugin is not implemented on android

### ISSUE THREAD

**Issue by aekasitt** [capacitor-community/barcode-scanner#232]
**Describe the bug**
Not at liberty to share the repo at the moment. The bug is the fact that BarcodeScanner plugin itself, not its functions, never get defined or attached to the built CapacitorJS app. I have followed through every step on the README and make sure to use the right version of lib and capacitor (see below). 

**To Reproduce**
I set my codebase to toast error message using `vue-toastification` So when I mount the vue component with the "BarcodeScanner" the modal pops up and begin scanning. Attached codebase below:

```
import { BarcodeScanner, SupportedFormat } from '@capacitor-community/barcode-scanner'
import { modalController } from '@ionic/vue'
import { onMounted } from 'vue'
import { useToast } from 'vue-toastification'
...
// funcs
let dismiss = async () => {
  await Promise.all([
    BarcodeScanner.stopScan().catch(() => void 0),
    modalController.dismiss(null, 'cancel')
  ])
}

// lifecycle hooks
onMounted(async () => {
  let hasPermission = await BarcodeScanner.checkPermission({ force: true })
    .then((permission: { granted?: boolean }) => permission.granted)
    .catch((err: {message: string}) => toast.error(err.message) || false)
  if (!!hasPermission) {
    let prepared = await BarcodeScanner.prepare()
      .then(() => true)
      .catch((err: { message: string }) => toast.error(err.message) || false)
    if (!prepared) return await dismiss()
    let mask = document.getElementById('mask')
    let videoNode = document.getElementById('video')
    let container = videoNode ? videoNode.parentElement : null
    if (!!mask && !!videoNode) {
      mask.insertAdjacentElement('beforeend', videoNode)
    }
    if (!!container) {
      document.body.removeChild(container)
    }
    let result = await BarcodeScanner
      .startScan({ targetedFormats: [SupportedFormat.QR_CODE] })
      .catch(err => toast.error('Errored scanning') || false)
    if (!result) return await dismiss()
    // @ts-ignore
    if (result.hasContent) {
      await BarcodeScanner.stopScan().catch(() => void 0)
      // @ts-ignore
      await modalController.dismiss(result.content, 'success')
    }
  } else {
    toast.warning('Not permitted')
    await dismiss()
  }
})
```

**Expected behavior**
To make sure this bug does not get dismissed for faulty process setup or ionic visibility, I make sure to get it working on web environment. (Chrome only, not Firefox) Attached is the expected behavior.

<img width="400" alt="web-barcode-scanner" src="https://user-images.githubusercontent.com/3035165/235573391-7cb51149-d49d-40a5-a9e3-e74144ab5f74.png">

**Screenshots**
<img width="400" alt="android-barcode-scanner" src="https://user-images.githubusercontent.com/3035165/235574723-de7405c4-2b3f-4bb9-86f2-7c560dccdbb2.png">

**Version**
- `@capacitor/core`: 4.8.0
- `@capacitor/android`: 4.8.0
- `@capacitor-community/barcode-scanner`: 3.0.3

**Desktop (please complete the following information):**
- OS: `macOS Ventura Version 13.0.1`
- Browser: `Chrome`
- Version: `112.0.5615.137 (Official Build) (arm64)`

**Smartphone (please complete the following information):**
- Device: `OnePlus 7` (GM1900) and `Android Emulator` on MacBook Pro M1 ("system-images;android-33;google_apis;arm64-v8a")
- OS: `HydrogenOS` (OP7) and `Stock Android` (Emulator)
- Browser: N/A
- Version: `Android Version 11` (OP7) and N/A
- WebView: `Android System WebView (112.0.5615.136)`

**Additional context**
Seems I may be redirected toward having multiple `package.json` file on my monorepo but I can assure that is not the case.
Attached is the outputs of the `npx cap sync` process.
<img width="557" alt="capacitor-plugins" src="https://user-images.githubusercontent.com/3035165/235575640-ee988535-b2d2-4e7c-92ee-e53e11c63551.png">

**Comment by aekasitt** [comment]
Noted with thanks. You can also assume I had been testing "clean-ups" with the following setup permutations as well.
`Node version`: [16, 18] (unable to use node v14 because `vue-tsc` does not build)
`Package manager`: [npm, yarn]
`@ionic/core` & `@ionic/vue` & `@ionic/vue-router`: [6.7.3, 6.7.4, 7.0.3]
`@capacitor/android` & `@capacitor/cli` & `@capacitor/core`: [4.1.1, 4.3.0, 4.5.0, 4.6.0, 4.7.0, 4.8.0]

With no luck.

If you have any idea what is the culprit for the unexpected build behavior, whether it's using an `aarch64` build environment, or including a cordova plugin, using latest @capacitor/* libs or latest @ionic/*, it would be very helpful.

**Comment by aekasitt** [comment]
The more I look into it, the more I find that my `android` build has none of the plugins defined in build steps.

Will pursue workaround recommended by Ionic Troubleshooting recommendations instead.

- https://capacitorjs.com/docs/android/troubleshooting#plugin-not-implemented
- https://github.com/ionic-team/capacitor/issues/1655#issuecomment-579229390
- https://stackoverflow.com/questions/55894716/how-to-package-a-hosted-web-app-with-ionic-capacitor

**Comment by thegnuu** [comment]
@aekasitt I think this is a good place to start with yes, I am pretty sure it has something to do with the Android setup. One thing came to my mind that helped me once I had this issue was to resync my android studio project with the gradle files. Maybe this might help in your case as well. Unfortunately I don't really have other suggestions.

If you can resolve your issue, it would be awesome if you could post a quick note here, it might really help if someone else runs into this problem in the future!

Thanks!
