### ISSUE TITLE
Capacitor 5

### ISSUE THREAD

**Issue by AE1NS** [capacitor-community/barcode-scanner#233]
https://capacitorjs.com/docs/next/updating/plugins/5-0

**Comment by BC-M** [comment]
Link is broken. Here is the new one: https://capacitorjs.com/docs/updating/plugins/5-0

**Comment by hauserkristof** [comment]
That would be nice!

@thegnuu feel free to tag me, if you need some testing about this!

**Comment by AE1NS** [comment]
One more thing. Could you please update the package.json to reference the latest capacitor versions. Unfortunately I forgot to upadte it.
