### ISSUE TITLE
Is capacitor community barcode scanner compatible with android 6?

### ISSUE THREAD

**Issue by sonnywirawan** [capacitor-community/barcode-scanner#236]
Is capacitor community barcode scanner compatible with android 6? My camera doesn't work on android 6, My camera permission is active but the camera still doesn't work. But everything works fine on devices with android 8
![bugs barcode scanner (permissions)](https://user-images.githubusercontent.com/60124244/236131296-05d853d0-4301-4ebc-8c54-fe11442c98ae.jpeg)
![bugs barcode scanner](https://user-images.githubusercontent.com/60124244/236131306-90210e00-73ff-4fa8-b6a9-3fbf76d4a65e.jpeg)

**Comment by thegnuu** [comment]
ZXing Android Embedded which is used for Android in this project requires SDK 24+, there is an info in the docs which says that if you downgrade zxing:core to 3.3.0 it should work on older versions. This "fix" is already implemented in this plugin, but if this is not working there is not much I can/will do. Android 6 was released in 2015 and reached EOL in 2018 with a current approximate usage of 1.6% of all devices ;)

The upcoming ML-Kit version requires a minimum of SDK 19, it might be possible that this version will work on your device with even better results ;) If you want you can make a test with the `ml-kit` branch. My current plan is to release a beta version of this implementation next Tuesday.

**Comment by thegnuu** [comment]
@sonnywirawan you can test version `v5.0.0-beta.1` and see if it might work with Android 6, but this version requires Capacitor 5 :)
