### ISSUE TITLE
v4.0.0 has the incorrect capacitor version in peerDependencies

### ISSUE THREAD

**Issue by medbenmakhlouf** [capacitor-community/barcode-scanner#238]
**Describe the bug**

I tried to install v4.0.0 under my project that's using capacitor v5

npm ERR! peer @capacitor/core@"^4.5.0" from @capacitor-community/barcode-scanner@4.0.0
npm ERR! node_modules/@capacitor-community/barcode-scanner
npm ERR!   @capacitor-community/barcode-scanner@"4.0.0" from the root project

**To Reproduce**

1. `npm i @capacitor-community/barcode-scanner@4.0.0`

**Expected behavior**

I think we should update under package.json

``` javascript
  "peerDependencies": {
    "@capacitor/core": "^5.0.0"
  }
```

**Version**
[e.g. v4.0.0]

**Comment by thegnuu** [comment]
Fixed in `v4.0.1`! For some reasons I only updated it in the pre-release version...
