### ISSUE TITLE
Update to @capacitor/core@"^5.0.0

### ISSUE THREAD

**Issue by NeluQi** [capacitor-community/barcode-scanner#240]
npm ERR! Found: @capacitor-community/barcode-scanner@3.0.3
npm ERR! node_modules/@capacitor-community/barcode-scanner
npm ERR!   @capacitor-community/barcode-scanner@"^4.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @capacitor-community/barcode-scanner@"^4.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @capacitor/core@5.0.3
npm ERR! node_modules/@capacitor/core
npm ERR!   peer @capacitor/core@"^5.0.0" from @capacitor-community/barcode-scanner@4.0.1
npm ERR!   node_modules/@capacitor-community/barcode-scanner
npm ERR!     @capacitor-community/barcode-scanner@"^4.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by jcesarmobile** [comment]
looks like you already have the version 3 installed, try uninstalling it first and then install latest
```
npm uninstall @capacitor-community/barcode-scanner
npm install @capacitor-community/barcode-scanner@latest
```
