### ISSUE TITLE
Scanner does not appear on my Ionic v7 app

### ISSUE THREAD

**Issue by 92lexus** [capacitor-community/barcode-scanner#247]
**Describe the bug**
I am trying to use the barcode scanner in my Ionic app, and have configured everything the way it is written in the docs, but somehow the barcode scanner just does not show up. 

I am using Ionic v7 and Capacitor v4.7.0, hence I am using version 3.0.3 of your package. 

I have followed your advice I have inspected my DOM, but this does not add the div I should be able to see. Note that it does ask me for my permission to use the camera and when accepted it also says that it uses the camera, but there is just no overlay. 

I will try updating the Capacitor version including the version of the package. 

**To Reproduce**

Just try every step from the Installation guide along with the versions I am using to see the issue. 

**Expected behavior**
Overlay should display. 

**Screenshots**

**Version**
v.3.0.3

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.6 
- Browser Chrome
- Version 113.0.5672.126

**Smartphone (please complete the following information):**

- Device: chrome://inspect
- Browser: chrome

**Additional context**

**Comment by DanielCastilloGT** [comment]
I was facing the same issue. Even though I wasn't seeing the DIV it is supposed to add to the DOM I just added a display:none; to the class scanner-active as the documentation suggests and it worked.

```
body.scanner-active {
    --background: transparent;
    --ion-background-color: transparent;
    display: none;
}
```

**Comment by JanMisker** [comment]
No div will be added, the camera is in a native view behind the webview.
