### ISSUE TITLE
need help to use barcode scanner

### ISSUE THREAD

**Issue by jw-redpanda** [capacitor-community/barcode-scanner#26]
I am new to capacitorjs and trying out your plugin BarcodeScanner.

Followed the instructions, defining build.gradle, adding BarcodeScanner.class in MainActivity.
Also, run 'ionic build; ionic cap copy; ionic cap sync' and then re-compile and run on Android device.
In the Ionic App, I have a service providing startScan() function that will be trigger by a user click:

```
  public startScan = async () => {
    console.log(`here in startScan()`);
    // const { BarcodeScanner } = Plugins;
    BarcodeScanner.hideBackground(); // make background of WebView transparent
    const result = await BarcodeScanner.startScan(); // start scanning and wait for a result
    // if the result has content
    if (result.hasContent) {
      console.log(result.content); // log the raw scanned content
    }
  }

```

However, it seems it has no function at all.  After clicked and called the function, it has no scanning window popped.  Can anyone help to give me some hints?  Thanks.

**Comment by tripodsgames** [comment]
You need to hide every element on your document.
I implemented in the follow way using css and js:

```css
.scanner-ui { display: none; }
.scanner-hide { visibility: visible; }

body.qrscanner { background-color: transparent; }
body.qrscanner .scanner-ui { display: block; }
body.qrscanner .scanner-hide { visibility: hidden; }
```
I made the scanner interface inside a div with `.scanner-ui` class to hide it when the scanner is not enabled.
Then i put the `.scanner-hide` class in my `<ion-app>` to hide the view when the scanner is enabled.

App Component HTML:
```html
<ion-app class="scanner-hide">
...App View
</ion-app>

<div class="scanner-ui">
...Scanner Interface
</div>
```

When the scanner is open i added the `.qrscanner` class to the `<body>`, this will make the interface visible and the `<ion-app>` invisible.

To add or remove the `.qrscanner` class:
```javascript
//ADD
document.body.classList.add("qrscanner");
//REMOVE
document.body.classList.remove("qrscanner");
```

**Comment by jw-redpanda** [comment]
Thanks @tripodsgames!

I tried out your clever way to show/hide the ionic pages that may block the barcode camera view.
It seems to me the code below cannot hide the ionic/angular pages... don't know if it is Angular that does not allow direct access to DOM.
```
document.body.classList.add("qrscanner");
document.body.classList.remove("qrscanner");

```

**Comment by tripodsgames** [comment]
You need to call this in the Javascript
```javascript
BarcodeScanner.hideBackground(); // make background of WebView transparent
document.body.classList.add("qrscanner"); // add the qrscanner class to body
const result = await BarcodeScanner.startScan(); // startscan
document.body.classList.remove("qrscanner"); // remove the qrscanner from the body
```

**Comment by jw-redpanda** [comment]
Your help is superb @tripodsgames! you saved me from the middle of the sea 😁😎

For those who are newbies trying out this plugin, on top of the Ionic/Angular [tutorial](https://ionicframework.com/docs/angular/your-first-app).  The detailed steps:
1. clone the [repo](https://github.com/ionic-team/photo-gallery-capacitor-ng)
2. cd tutorial-photo-gallery-angular
3. edit package.json because of an Andriod studio 4.x [issue](https://stackoverflow.com/questions/61066014/ionic-capacitor-app-give-me-lots-of-errors).
4. npm install 
5. npm install @capacitor-community/barcode-scanner
6. copy from [here](https://raw.githubusercontent.com/capacitor-community/barcode-scanner/main/android/src/main/java/com/dutchconcepts/capacitor/barcodescanner/BarcodeScanner.java) and create a java file under tutorial-photo-gallery-angular/android/app/src/main/java
```
'com
└── dutchconcepts
    └── capacitor
        └── barcodescanner
            └── BarcodeScanner.java
```
7. edit tutorial-photo-gallery-angular/android/app/build.gradle (only added those indicated below)
```
repositories {
    // add below
    mavenCentral()
}
dependencies {
   // add below
    implementation('com.journeyapps:zxing-android-embedded:4.1.0') { transitive = false }
    implementation 'com.google.zxing:core:3.3.0'
}
```
Edit tutorial-photo-gallery-angular/android/app/src/main/java/io/ionic/pg/ng/cap/MainActivity.java, add lines as indicated.
```java
package io.ionic.pg.ng.cap;
import android.os.Bundle;
import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;
import java.util.ArrayList;

// add this line
import com.dutchconcepts.capacitor.barcodescanner.BarcodeScanner;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Add this line
      add(BarcodeScanner.class);
    }});
  }
}
```

8. Follow instructions suggested by @tripodsgames:
Edit tutorial-photo-gallery-angular/src/global.scss, add these lines
```css
.scanner-ui { display: none; }
.scanner-hide { visibility: visible; }

body.qrscanner { background-color: transparent; }
body.qrscanner .scanner-ui { display: block; }
body.qrscanner .scanner-hide { visibility: hidden; }

```
9. Edit tutorial-photo-gallery-angular/src/app/app.component.html
```html
<ion-app  class="scanner-hide">
  <ion-router-outlet></ion-router-outlet>
</ion-app>

<div class="scanner-ui">
  ...Scanner Interface
</div>
```
10. Add a startScan() function to photo services.
edit tutorial-photo-gallery-angular/src/app/services/photo.service.ts
```typescript
  // add a function to trigger barcode scanning
  public async startScan() {
    // const { BarcodeScanner } = Plugins;
    BarcodeScanner.hideBackground(); // make background of WebView transparent
    document.body.classList.add("qrscanner"); // add the qrscanner class to body
    const result = await BarcodeScanner.startScan(); // startscan
    document.body.classList.remove("qrscanner"); // remove the qrscanner from the body    
   
    // if the result has content
    if (result.hasContent) {
     console.log(`barcode scanning result=${result.content}`); // log the raw scanned content
    }
  }
```
11. Add a top FAB button on tab2 to invoke barcode capacitor plugin
Edit tutorial-photo-gallery-angular/src/app/tab2/tab2.page.html

```html
  <ion-fab vertical="top" horizontal="center" slot="fixed">
    <ion-fab-button (click)="photoService.startScan()">
      <ion-icon name="camera"></ion-icon>
    </ion-fab-button>
  </ion-fab>

```
12. when all edits are done. 
ionic cap sync
13. compile and run on an Android device

Hope the above would provide some hints in getting started to use capacitorjs.

**Comment by tafelnl** [comment]
Thanks for all the help guys. Will take a look if I can put this in the docs somewhere.

**Comment by wurst44** [comment]
I am doing everything of the above.
I can scan barcodes but it does not seem to show an camera **overlay** which seems to exsist?

```
<ion-app  class="scanner-hide">
  <ion-router-outlet></ion-router-outlet>
</ion-app>

<div class="scanner-ui">
</div>
```
```
BarcodeScanner.hideBackground(); 
document.body.classList.add("qrscanner");
const result = await BarcodeScanner.startScan();
document.body.classList.remove("qrscanner");
```
```
.scanner-ui { display: none; }
.scanner-hide { visibility: visible; }

body.qrscanner { background-color: transparent; }
body.qrscanner .scanner-ui { display: block; }
body.qrscanner .scanner-hide { visibility: hidden; }
```
thx for your help!

**Comment by tripodsgames** [comment]
You need to create your own camera overlay using css and html inside the scanner-ui div.

https://github.com/capacitor-community/barcode-scanner/blob/main/examples/scan-area-layout/index.html

**Comment by javatheist** [comment]
@jw-redpanda I honestly appreciate all your effort. I'm convinced that your endeavour to improve the community's understanding was very beneficial from some developers' perspectives.
After all, I'd like to point out that - just from my point of view - there is no need to take steps 6 and 7. Keeping the AndroidManifest as is should be perfectly fine too.
My approach was to npm install Capacitor's CameraPreview and BarcodeScanner, add both of them to your index.ts. As soon as the CameraPreview plugin provides you with some sort of stream, the BarcodeScanner's async startScan works just fine.
In the end, I came up with a web interface of the BarcodeScanner which made use of pngjs, jsqr and a promise which processed a specific loop until resolve/reject.

Anyway, maybe you would like to have another go with your approach.

Regards, Peter

**Comment by paulburz** [comment]
https://www.youtube.com/watch?v=8GXfjDUCYjU
Here's an ionic example I used as well :)

**Comment by tafelnl** [comment]
Closing this issue since the docs are a little more elaborate now and also references this issue and #7

**Comment by braincomb** [comment]
Thanks @tripodsgames , this works great!

Since we are hiding the whole `<body>` tag, do you know if it's somehow possible to apply certain effects, e.g. blur() or opacity, to the whole scanner screen, but leave the centered box overlay normal?

> You need to hide every element on your document. I implemented in the follow way using css and js:
> 
> ```css
> .scanner-ui { display: none; }
> .scanner-hide { visibility: visible; }
> 
> body.qrscanner { background-color: transparent; }
> body.qrscanner .scanner-ui { display: block; }
> body.qrscanner .scanner-hide { visibility: hidden; }
> ```
> 
> I made the scanner interface inside a div with `.scanner-ui` class to hide it when the scanner is not enabled. Then i put the `.scanner-hide` class in my `<ion-app>` to hide the view when the scanner is enabled.
> 
> App Component HTML:
> 
> ```
> <ion-app class="scanner-hide">
> ...App View
> </ion-app>
> 
> <div class="scanner-ui">
> ...Scanner Interface
> </div>
> ```
> 
> When the scanner is open i added the `.qrscanner` class to the `<body>`, this will make the interface visible and the `<ion-app>` invisible.
> 
> To add or remove the `.qrscanner` class:
> 
> ```js
> //ADD
> document.body.classList.add("qrscanner");
> //REMOVE
> document.body.classList.remove("qrscanner");
> ```

**Comment by tripodsgames** [comment]
> Thanks @tripodsgames , this works great!
> 
> Since we are hiding the whole `<body>` tag, do you know if it's somehow possible to apply certain effects, e.g. blur() or opacity, to the whole scanner screen, but leave the centered box overlay normal?
> 
> > You need to hide every element on your document. I implemented in the follow way using css and js:
> > ```css
> > .scanner-ui { display: none; }
> > .scanner-hide { visibility: visible; }
> > 
> > body.qrscanner { background-color: transparent; }
> > body.qrscanner .scanner-ui { display: block; }
> > body.qrscanner .scanner-hide { visibility: hidden; }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I made the scanner interface inside a div with `.scanner-ui` class to hide it when the scanner is not enabled. Then i put the `.scanner-hide` class in my `<ion-app>` to hide the view when the scanner is enabled.
> > App Component HTML:
> > ```
> > <ion-app class="scanner-hide">
> > ...App View
> > </ion-app>
> > 
> > <div class="scanner-ui">
> > ...Scanner Interface
> > </div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When the scanner is open i added the `.qrscanner` class to the `<body>`, this will make the interface visible and the `<ion-app>` invisible.
> > To add or remove the `.qrscanner` class:
> > ```js
> > //ADD
> > document.body.classList.add("qrscanner");
> > //REMOVE
> > document.body.classList.remove("qrscanner");
> > ```

You have to find a way to blur the parent element without affecting the child.
I don't know how to do this :(

**Comment by jkd2bleu** [comment]
This worked perfectly for me https://github.com/Nykz/Ionic-6-qrcode
