### ISSUE TITLE
"TypeError: undefined is not an object" [...] / Error: method not available in web

### ISSUE THREAD

**Issue by YourPenguin** [capacitor-community/barcode-scanner#30]
So, I'm using this plugin for a while, but now i stared a new web app project with vue and the quasar framework.
I imported the plugin in the <script> tag:

```
import { Plugins, CameraResultType } from '@capacitor/core';

const { BarcodeScanner } = Plugins
```

and want a function to return the scanned data like:

```
async GetScanQrCode () {
      const camPermission = await BarcodeScanner.checkPermission({ force: true })
      if (!camPermission.granted) {
        return false
      }
      const result = await BarcodeScanner.startScan()
      if (result.hasContent) {
        return result.content
      }
    }
```

In my last project I did it the same all the way, so im pretty confused that on my iPhone 8 i get this message: 

https://prnt.sc/11uywim

So it immediately fails. This also happens on my Android device, a Xiaomi Mi Note 10

So... what could be the problem here?
I already updated all my dependencies the lastest version and tried everything that comes to my mind, i just don't see why it's still working in my old project but not in this one.
In both projects im using **vue version 2.6.12**

Also, when i try to import the plugin this way...

`import { BarcodeScanner } from '@capacitor-community/barcode-scanner'`

... I always get the message **"Error: method not available in web"**, either I'm running on a mobile or not.
This is very confusing and I really hope someone can help me out here.

Thanks in advance!

**Comment by tafelnl** [comment]
It looks like the native methods of Capacitor are not being loaded into the webapp. That could be caused by various things. For example: 

- you are not running the app in a native shell (like a .apk for example, or built from Android Studio or Xcode)
- you are not using capacitor correctly (maybe because quasar does not import it by default)

**Comment by YourPenguin** [comment]
> It looks like the native methods of Capacitor are not being loaded into the webapp. That could be caused by various things. For example:
> 
> * you are not running the app in a native shell (like a .apk for example, or built from Android Studio or Xcode)
> * you are not using capacitor correctly (maybe because quasar does not import it by default)

Not running the app native isn't a problem in my earlier project, Xcode works fine with a direct build over lightning cable, as well as android studio.
I doubt that i don't use capacitor correctly because the camera API works just fine.
I am really not able to tell where the difference lies, i compared the source codes, copied the nodes_modules folder etc.

**Comment by tafelnl** [comment]
Could you share a repo for reproduction?

**Comment by YourPenguin** [comment]
It's fine now, apparently the only issue was that the package.json file hasn't updated itself so there was no "@capacitor-community/barcode-scanner" under "dependencies"

```
"dependencies": {
    "@capacitor-community/barcode-scanner": "^1.2.1",
    "@capacitor/core": "^2.4.7",
    "@fortawesome/fontawesome-pro": "^5.15.3",
    "@quasar/extras": "^1.10.2",
    "capacitor-qrscanner": "0.0.2",
    "axios": "^0.21.1",
    "dexie": "^3.0.3",
    "boot": "^0.8.2",
    "core-js": "^3.10.0",
    "ping.js": "^0.3.0",
    "jspdf": "^2.3.1",
    "quasar": "^1.15.10",
    "vue-i18n": "^8.24.2"
  }
```

This way it is working now, thanks for your time tho!

**Comment by tafelnl** [comment]
No worries, glad it's working now!

**Comment by NicoP-S** [comment]
@YourPenguin i am faceing the same problem like you did `Error: method not available in web`

Installation:
```
cd src-capacitor
npm install @capacitor-community/barcode-scanner
npx cap sync
quasar dev -m capacitor -T android 
// then start android emulator in android studio
```

src-capacitor/package.json
```
  "dependencies": {
    "@capacitor-community/barcode-scanner": "^1.2.1",
    "@capacitor/android": "^2.5.0",
    "@capacitor/cli": "^2.0.0",
    "@capacitor/core": "^2.0.0"
  }
```

I tried your alternative way of importing but BarcodeScanner is undefined.
```
<script>
// import { BarcodeScanner } from '@capacitor-community/barcode-scanner';
// ^^^  Error: method not available in web
import { Plugins } from '@capacitor/core';
const { BarcodeScanner } = Plugins

export default {
  methods: {
    async start() {
      console.log(Plugins);
      console.log(BarcodeScanner) // undefined :(
      
      BarcodeScanner.hideBackground(); // make background of WebView transparent

      const result = await BarcodeScanner.startScan(); // start scanning and wait for a result

      // if the result has content
      if (result.hasContent) {
        alert(result.content); // log the raw scanned content
      }
    }

  }
}
</script>
```
https://github.com/NicoP-S/barcodescan/blob/2c70d98ca95ec3aa142497a9a5a27d2f7f445817/src/pages/Native.vue#L7-L34

Have you done anything other then me? 
Here is a test repo: https://github.com/NicoP-S/barcodescan 
https://github.com/NicoP-S/barcodescan/blob/master/src/pages/Native.vue
