### ISSUE TITLE
feat: add configurability to just pause the scanner (while keeping the view open) on scan rather than destroying it.

### ISSUE THREAD

**Issue by milanharia** [capacitor-community/barcode-scanner#33]
Right now the current implementation of the scanner is to automatically destroy it for battery and performance reasons. In the source code there is currently a destroy function which dismantles the camera and hides the viewfinder. It would be great if we could configure this functionality to just pause the scanner when a barcode is scanned, and to keep the camera viewfinder open, something like the function below.

private func destroy() {
        self.shouldRunScan = false
    }

**Comment by tafelnl** [comment]
Fair enough. Will look into it while developing continuous scanning mode.

**Comment by hellokingdom** [comment]
@tafelnl continuously scanning barcodes would be great and to @milanharia point it would be useful to have the ability to set a cool down time between scans (i.e how long before the scanner becomes active).

Would also be useful to expose a method which can be used to distinguish between the scanning being 'active' or 'paused' to allow fine control over the UI overlay the user is shown between successful scans.

**Comment by tafelnl** [comment]
@hellokingdom active/pause event is indeed essential I think. However I do think a cool down timer would be a little out of scope for this project. It wouldn't be to difficult to implement such a thing in JS however, with a simple timeout for example.

**Comment by hellokingdom** [comment]
@tafelnl Yeah that makes sense. If we have events for pausing and activating the scanner we can keep the UI logic in the JS layer where it belongs.

**Comment by m-bagnarelli** [comment]
Hi, any updates on this? :). I really need it. 
@milanharia Could you make it somehow?

**Comment by rulaman123** [comment]
I have done that. It is possible. Don't know if it's perfect but in my case its working fine.
You have to edit the BarcodeScanner.java (capacitor-community\barcode-scanner\android\src\main\java\com\dutchconcepts\capacitor\barcodescanner\BarcodeScanner.java).

Go to the method "Override public void barcodeResult(BarcodeResult barcodeResult)" and delete
`destroy();`
Then the scanner view will not pause any more.

after that you can create a new method for scanning again.
```
private void scanAgain() {
    BarcodeCallback b = this;
    getActivity()
      .runOnUiThread(
        () -> {
            mBarcodeView.decodeSingle(b);
        }
      );
  }

```

After that create a new plugin method
```
  @PluginMethod
  public void startScanAgain(PluginCall call) {
    saveCall(call);
    scanAgain();
  }
```

And the last step is to add the newly created method to the interface (capacitor-community\barcode-scanner\dist\esm\definitions.d.ts):
go to the method "export interface BarcodeScannerPlugin" and add
`startScanAgain(): Promise<ScanResult>;`

And now you can start a new scan with "startScanAgain()".
I have done that by using a modal for my scan result and every time the model will dismiss the next scan is starting.
Dont forget to close the scanner, e.g. when leaving the site.

**Comment by thegnuu** [comment]
PR #93 which should resolve this by adding a continuous scanning feature is now merged to the main branch, I will make a few tests next week and release `2.1.0` if everything works as expected!
