### ISSUE TITLE
feat: Add support for toggling torch

### ISSUE THREAD

**Issue by tafelnl** [capacitor-community/barcode-scanner#34]
I should look into PR https://github.com/capacitor-community/barcode-scanner/pull/32. Then add support for iOS. And finally release it.

**Comment by arnotixe** [comment]
I'm very interested in this :)

Found out I can npm install git://github.com/capacitor-community/barcode-scanner.git#feat/torch
and then check out the repo elsewhere and build the library + copy in the resulting dist/ folder

Works on Android! (can only turn ON though, for some reason, turning off is a no-go :thinking: )

**Comment by arnotixe** [comment]
> Works on Android! (can only turn ON though, for some reason, turning off is a no-go thinking )

Just found out how to fix the torch on/off and created PR https://github.com/capacitor-community/barcode-scanner/pull/73

**Comment by arnotixe** [comment]
Retired the previous PR and created the branch-clean https://github.com/capacitor-community/barcode-scanner/pull/75 
feat/torch now would support both android and iOS.

**Comment by thainvo** [comment]
Are there any plans of adding flashlight support to the plugin in the near future? It'd be a big help in the case of our application and although there are some PRs including these changes, they all concern version 1.2.1 of the plugin, which is incompatible with Capacitor 3.

**Comment by avinmaster** [comment]
Now I'm using `@ionic-native/barcode-scanner`.

**Comment by cies** [comment]
Does this do the trick? https://github.com/capacitor-community/barcode-scanner/pull/78

**Comment by arnotixe** [comment]
I vote for closing my #75 and accepting #78, as it is more complete and looks like it's written by someone who actually knows swift :)

**Comment by thegnuu** [comment]
PR #78 is merged an `2.1.0` will be released next week
