### ISSUE TITLE
Scanning with Android off a secondary LCD screen

### ISSUE THREAD

**Issue by tpharaoh** [capacitor-community/barcode-scanner#37]
**Describe the bug**
This is not really a bug, but the best description I can give. I have a small IOT with LCD screen, which shows a pairing QR code. In IOS it scans immediately, no issues.

In Android, the scanner opens but it doesn't read the code. Obviously refresh rate may be affecting it. When I scan off my monitor, no problem.

**To Reproduce**
It seems strictly related to the refresh on the LCD, because the identical QR code below displayed on a monitor works.

**Version**
1.2.1

Android
Samsung Note 10

![image](https://user-images.githubusercontent.com/2931452/117975027-eb2af900-b336-11eb-9f15-ac691fb92442.png)

**Comment by tpharaoh** [comment]
one suggestion from a colleague was if I can reduce resolution of camera, is there a was to do that?

**Comment by tpharaoh** [comment]
https://github.com/bitpay/cordova-plugin-qrscanner/issues/347

https://github.com/bitpay/cordova-plugin-qrscanner/issues/304

https://github.com/bitpay/cordova-plugin-qrscanner/issues/99

Seems its not related to the refresh at all, but rather to the color. I'll speak with the guy who wrote the firmware see if we can invert our code.

**Comment by tpharaoh** [comment]
So, those posts were the key, I contacted the guy who made the FW in our division, and we inverted QR and it worked...

**Comment by tafelnl** [comment]
I confirmed that only iOS is able to scan inverted barcodes right now. Did some research and found a way to make Android also support inverted barcodes. Will release a version with support for this sometime soon. So stay tuned!
