### ISSUE TITLE
Empty response object when checking permissions with { force: false } option

### ISSUE THREAD

**Issue by JZubero** [capacitor-community/barcode-scanner#45]
As stated in the docs, it should be possible to check the permissions without triggering the native system dialog:

```typescript
const status = await BarcodeScanner.checkPermission({ force: false });
```

While I assumed the `status` const would hold all fields from the `CheckPermissionResult` interface (see below), I am receiving an empty object `{}`. In theory, the empty object **does** comply with the interface typing since all properties are optional but it does not make much sense though. Plus the docs are indicating that the properties should be available when checking with `force: false`.

```typescript
// CheckPermissionResult interface
interface CheckPermissionResult {
    granted?: boolean;
    denied?: boolean;
    asked?: boolean;
    neverAsked?: boolean;
    restricted?: boolean;
    unknown?: boolean;
}
```

---

I am using the latest version (2.0.0) of the plugin with Capacitor 3.0.1. Tested on an Android emulator (Google Pixel 2).

**Comment by tafelnl** [comment]
Hm, I am not sure what to think about this. It would also, in a strict sense, introduce a breaking change to the API. It could be that people are checking for something like `if (typeof status.granted !== 'undefined')`. So if we decide to change it, it should be done with the next major release.

The way of handling is a more common pattern found in other libraries as well. I agree with you that it maybe not is the best or most beautiful way. But IMHO it might also be a little bit too nitpicky. How high of importance is this issue for you?

**Comment by tafelnl** [comment]
Yes you are correct about the first three things.

Regarding the fourth point: only `asked` will never be set with `force: false`. `restricted`, `neverAsked` and `unknown` can actually always be returned.

So as long as `result.denied` is not set or false, you should be able to re-request the permission. Additionally you can use the other parameters to determine whether you want to show a message first before actually requesting the permission. For example: if `result.neverAsked` is not set or false and `result.granted` is also not set or false, the user has apparently already been requested the permission but he did not accept it. So you may want to show some additional information.

I think I should put some more information about this in the docs to clear things up. Would that also satisfy this issue in general?

**Comment by JZubero** [comment]
> I think I should put some more information about this in the docs to clear things up. Would that also satisfy this issue in general?

Yes, I'd say so. A little more information about this could help to prevent any confusion :+1:
