### ISSUE TITLE
WebView transparent in react

### ISSUE THREAD

**Issue by blatoo** [capacitor-community/barcode-scanner#61]
**Describe the bug**
I want to use this QRCode Scanner with react, and tried on the Android, but it doesn't popup the scanner view. I searched the problem, it should be the Webview transparent problem...But I didn't find the solution for Ionic React

**To Reproduce**
```
export const QRScanner: React.FC = () => {
  const startScan = async () => {
    BarcodeScanner.hideBackground()

    const result = await BarcodeScanner.startScan()

    if (result.hasContent) {
      console.log(result.content)
    }
  }

  const stopScan = () => {
    BarcodeScanner.showBackground()
    BarcodeScanner.stopScan()
  }

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonButtons slot="start">
            <IonMenuButton />
          </IonButtons>
          <IonTitle>QRScanner</IonTitle>
        </IonToolbar>
      </IonHeader>

      <IonContent fullscreen>
        <IonRow>
          <IonButton onClick={startScan}>Start</IonButton>
          <IonButton onClick={stopScan}>Cancel</IonButton>
        </IonRow>
      </IonContent>
    </IonPage>
  )
}

```

**Expected behavior**
The Scan View should coming, but it doesn't! But I got notice from Android, that the camera should already working... 

**Version**
    "@capacitor/android": "^3.1.1",
    "@capacitor-community/barcode-scanner": "^2.0.1",

**Smartphone (please complete the following information):**
Android

**Comment by tafelnl** [comment]
Please try debugging it like this: https://github.com/capacitor-community/barcode-scanner#the-scanner-view-does-not-show-up

**Comment by blatoo** [comment]
> Please try debugging it like this: https://github.com/capacitor-community/barcode-scanner#the-scanner-view-does-not-show-up

Hi tafelnl, I did the debugger and find the problem in react, so I did a detailed youtube video for people who has later the same problem. 

https://youtu.be/6sxwMfNyJiI

Thanks so much for this great plugin and eagerly waiting for web implementation!

**Comment by ken2k** [comment]
Hi everyone,
Just to let you know that it works fine (version 2.1.1) using Ionic with both light and dark modes on my app, I just added "!important" to the following already required CSS lines so it doesn't break on dark mode:

```
body.scanner-active {
  --background: transparent !important;
  --ion-background-color: transparent !important;
}
```
