### ISSUE TITLE
feat: add support for using different cameras

### ISSUE THREAD

**Issue by mani-96** [capacitor-community/barcode-scanner#63]
Need ability to flip camera. Currently only back camera is opened that scans. Can some way be provided so that we can toggle between front or back camera programmatically.

**Comment by cies** [comment]
See the PR here: https://github.com/capacitor-community/barcode-scanner/pull/78

Hopefully it'll soon be merged.

**Comment by thegnuu** [comment]
I merged #94 and will release `2.1.0` next week, so I will close this issue for now...
