### ISSUE TITLE
Problem with startScan : class member cannot have the keyword 'const', ts (1248)

### ISSUE THREAD

**Issue by TOTOTO06** [capacitor-community/barcode-scanner#65]
import { Component } from '@angular/core';

import { BarcodeScanner } from '@capacitor-community/barcode-scanner';

@Component({
  selector: 'app-tab2',
  templateUrl: 'tab2.page.html',
  styleUrls: ['tab2.page.scss']
})
export class Tab2Page {

  constructor() {}

  const startScan = async () => {
    BarcodeScanner.hideBackground(); // make background of WebView transparent
  
    const result = await BarcodeScanner.startScan(); // start scanning and wait for a result
  
    // if the result has content
    if (result.hasContent) {
      console.log(result.content); // log the raw scanned content
    }
  };
}

**Comment by tafelnl** [comment]
This error is not actually related to this plugin. It is how TypeScript works in general. You should read up more about and try to get familiar with it, before going on with the implementation of this plugin. A good start would be for example reading this: https://stackoverflow.com/questions/36142879/const-keyword-in-typescript/41742589
