### ISSUE TITLE
Jest Issue - ReferenceError: capacitorExports is not defined

### ISSUE THREAD

**Issue by thequailman** [capacitor-community/barcode-scanner#67]
**Describe the bug**
When I test against a module using this plugin, jest throws an error after the import statement:
```
  ● Test suite failed to run

    ReferenceError: capacitorExports is not defined

    > 5 | import {BarcodeScanner} from "@capacitor-community/barcode-scanner";
        | ^
      6 | import {Capacitor} from "@capacitor/core";

      at Object.<anonymous> (node_modules/@capacitor-community/barcode-scanner/dist/plugin.js:68:7)
      at Object.<anonymous> (src/views/myview.ts:5:1)
      at Object.<anonymous> (src/views/myview.test.ts:3:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:261:3)
```

**To Reproduce**
Run jest against a module using this plugin

**Expected behavior**
No error from jest, I don't test this plugin using it.

**Version**
2.0.1

**Comment by thequailman** [comment]
Temporary workaround:

**jest.config.js**
```
module.exports = {
	moduleNameMapper: {
		"\\@capacitor-community/barcode-scanner": "<rootDir>/src/jest/noop.ts",
	},
}
```

**src/jest/noop.ts**
```
module.exports = "";
```

**Comment by pwespi** [comment]
Probably related to https://github.com/ionic-team/capacitor/issues/3972, https://github.com/capacitor-community/bluetooth-le/pull/14

**Comment by nasaleanhorea** [comment]
same issue here , all jest tests are failing

**Comment by mike-cao** [comment]
Is it just me or is anyone else experiencing this error when running their web app in general and not just with Jest? It used to be fine (as far as I know as it was working before) but perhaps some code updates I've recently made in my project seems to have caused my build (Ionic 5, Capacitor 3, Angular 12 with SSR) to get the "capacitorExports is not defined" message when compiled. As a temporary fix, I've commented out the lines referencing this plugin since I'm not using it in my PWA anyway, but I'd like to not have to always remember to uncomment when building the native versions. I'm thinking perhaps it's a TSconfig issue? Is there a workaround similar to the one for jest as @thequailman shared? Thanks in advance!

**Comment by leticiatomasio** [comment]
My workaround was to mock the BarcodeScanner Node.js module globally, similar to @wfairclough's solution.

1. First, I mocked the node module following Jest's instructions (https://jestjs.io/pt-BR/docs/manual-mocks):
2. 



2. Then, on my jest.config.ts, I mapped any module reference to the mock path.

```
moduleNameMapper: {
    '\\@capacitor-community/barcode-scanner':
      'libs/niemeyer/src/jest/__mocks__/@capacitor-community/barcode-scanner.js',
  },
```

**Comment by leticiatomasio** [comment]
My workaround was to mock the BarcodeScanner Node.js module globally, similar to @wfairclough's solution.

1. First, I mocked the Node module following Jest's instructions (https://jestjs.io/pt-BR/docs/manual-mocks) inside a __mocks__ directory:

libs/niemeyer/src/jest/__mocks__/@capacitor-community/barcode-scanner.js

```
jest.mock('@capacitor-community/barcode-scanner', () => {
  return {
    hideBackground: jest.fn(),
    startScan: jest.fn(),
    showBackground: jest.fn(),
    checkPermission: jest.fn(),
    openAppSettings: jest.fn(),
  };
});
```

2. Then, on my jest.config.ts, I mapped any module reference to the mock path.

```
moduleNameMapper: {
    '\\@capacitor-community/barcode-scanner':
      'libs/niemeyer/src/jest/__mocks__/@capacitor-community/barcode-scanner.js',
  },
```

**Comment by leticiatomasio** [comment]
My workaround was to mock the BarcodeScanner Node.js module globally, similar to @wfairclough's solution.

1. First, I mocked the Node module following Jest's instructions (https://jestjs.io/docs/manual-mocks) inside a __mocks__ directory:

libs/niemeyer/src/jest/__mocks__/@capacitor-community/barcode-scanner.js

```
jest.mock('@capacitor-community/barcode-scanner', () => {
  return {
    hideBackground: jest.fn(),
    startScan: jest.fn(),
    showBackground: jest.fn(),
    checkPermission: jest.fn(),
    openAppSettings: jest.fn(),
  };
});
```

2. Then, on jest.config.js, I mapped any BarcodeScanner module reference to the mock path.

```
moduleNameMapper: {
    '\\@capacitor-community/barcode-scanner':
      'libs/niemeyer/src/jest/__mocks__/@capacitor-community/barcode-scanner.js',
  },
```

**Comment by thegnuu** [comment]
For me it looks like mocking the module would be the right solution for this issue, proper tests will require a mocked module anyway since it is not testable otherwise by jest.

I will add @leticiatomasio 's solution to the docs next week!

**Comment by czabaj** [comment]
> @mike-cao I got the same issue with Next.js
> 
> The temporary workaround was to change `"main": "dist/plugin.js",` to `"main": "dist/plugin.cjs.js",` in package.json, which belongs to capacitor-community/barcode-scanner.

Or simply import from the dist w/o changing the lib code

```
import { BarcodeScanner } from "@capacitor-community/barcode-scanner/dist/plugin.cjs";
```

**Comment by thegnuu** [comment]
This should now finally be fixed, since `main` in `package.json` is now set to the`commonjs` version of the plugin :)

**Comment by alexnault** [comment]
@thegnuu I confirm; upgrading to [3.0.1](https://github.com/capacitor-community/barcode-scanner/releases/tag/v3.0.1) has fixed the issue for me. https://github.com/capacitor-community/barcode-scanner/commit/73db101b9a62bc31595f469ad4c5c4cc772fdc1b
