### ISSUE TITLE
[Android] Permission Request resolves immediately

### ISSUE THREAD

**Issue by ec-lmayr** [capacitor-community/barcode-scanner#71]
The promise when requesting the permission status / request always immediately resolves without waiting for the user input.

**To Reproduce**
If requesting the permission like below, `statusRequest.granted` will never be `true`, as the `checkPermission` promise resolves immediately.
```
 const statusRequest = await BarcodeScanner.checkPermission({ force: true });

  if (statusRequest.asked) {
    // system requested the user for permission during this call
    // only possible when force set to true
  }

  if (statusRequest.granted) {
    // the user did grant the permission now
    // ERROR this will never happen, if the user just now granted the permission
    return true;
  }

```
**Expected behavior**
The `await BarcodeScanner.checkPermission({ force: true })` should only resolve when the permission request is done. 

- OS: Android

I have looked through the Android code and added to paramaters to the savedReturnObject.
https://github.com/ec-lmayr/barcode-scanner/blob/main/android/src/main/java/com/dutchconcepts/capacitor/barcodescanner/BarcodeScanner.java

Once in line 407 (` this.savedReturnObject.put("resolve", "1");` ) and once in the permCallback in 467 (         `this.savedReturnObject.put("resolve", "2"); `).

It is always with `{ resolve: 1 }` resolved.
It seems like the `return` statement after calling `requestPermissionForAlias(PERMISSION_ALIAS_CAMERA, call, "cameraPermsCallback");` in line 391 is ignored? Event when it's called the call will be resolved in line 407. Never in 467.

Maybe this helps you somehow? Thanks for you work!
All the best,
lukas

**Comment by tafelnl** [comment]
I am not sure what you mean. Would you be able to elaborate? If I am calling that method with those parameters it will request the permission. It would be possible that indeed the permission is not requested, but then `result.denied` should be set to `true`. So you could check that.

Also which Android version are you using?

**Comment by ec-lmayr** [comment]
The issue is that `await BarcodeScanner.checkPermission({ force: true })` resolves immediately, when it should wait for the user until he or she chooses an option in the native dialog. 
It just returns the state of the permission, not the updated state, after the user has chosen.
Is this more clear?

**Comment by tafelnl** [comment]
Hmm, I should try to reproduce this. Please give me some time to figure this one out.

**Comment by ec-lmayr** [comment]
sure, thanks for your help!

on more thing: this is only relevant the first time. 
"User has never used the camera inside the app, then allows it."

**Comment by tafelnl** [comment]
What do you mean by that?

**Comment by ec-lmayr** [comment]
that it's only a relevant problem if the user has never been asked. and only for the flow "never asked" -> "user allows it"

because if it is denied/allowed already, there is no async process going on.

**Comment by BC-M** [comment]
Got the same issue. I tested it with a Xiamo Mi A2 Lite and Android 10. 

Like @ec-lmayr said, the promise returns immediately a empty object until the user pressed "never ask again". On iOS, the function works as desired.

**Comment by tolutronics** [comment]
The permission dialog is not executed the next time the app is launch even when the user chooses ONLY THIS TIME permission
