### ISSUE TITLE
Examples / Demo?

### ISSUE THREAD

**Issue by memic84** [capacitor-community/barcode-scanner#76]
Are there any resources / examples / demo's to test this app out?
Or maybe a list with apps that are built with this barcode-scanner, and are public?

... or maybe a simple APK for android, just to see it in action.

**Comment by JustCallMeMarly** [comment]
Here is an example i've found https://www.youtube.com/watch?v=8GXfjDUCYjU&t=840s
I hope this helps!

**Comment by memic84** [comment]
Thanks!
