### ISSUE TITLE
Not scanning barcode on android

### ISSUE THREAD

**Issue by wash-dev** [capacitor-community/barcode-scanner#77]
**Describe the bug**
I was trying to scan a barcode in android but not reading it at all. Sometimes I can scan but it takes several seconds to read the barcode.

Here is my code:

import { Component, AfterViewInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { AlertController } from '@ionic/angular';
import { BarcodeScanner } from '@capacitor-community/barcode-scanner';
import { ModalService } from 'src/app/services/modal.service';

@Component({
  selector: 'app-barcode-scan-model',
  templateUrl: './barcode-scan-model.component.html',
  styleUrls: ['./barcode-scan-model.component.scss'],
})
export class BarcodeScanModelComponent implements AfterViewInit, OnDestroy {

  result = null;
  scanActive = false;

  constructor(
    private alertCtrl: AlertController,
    private _cdf: ChangeDetectorRef,
    private modal: ModalService
  ) { }

  async ngAfterViewInit() {
    document.addEventListener('click', (evt) => {
      const target = evt.target as HTMLElement;
      if (target.id === 'closeScanner') {
        this.stopScan();
      }
    });
    await BarcodeScanner.prepare();
    this.startScan();
    this._cdf.detectChanges();
  }

  ngOnDestroy() {
    this.stopScan();
  }

  async startScan() {
    BarcodeScanner.hideBackground();
    document.body.classList.add('qrscanner');
    const allowed = await this.checkPermission();
    if (allowed) {
      this.scanActive = true;
      const result = await BarcodeScanner.startScan();
      if (result?.hasContent) {
        this.result = result.content;
      }
      document.body.classList.remove('qrscanner');
      BarcodeScanner.showBackground();
      this.scanActive = false;
    } else {
      document.body.classList.remove('qrscanner');
      BarcodeScanner.showBackground();
      this.dismiss();
    }
  }

  stopScan() {
    if (this.scanActive) {
      document.body.classList.remove('qrscanner');
      BarcodeScanner.showBackground();
      BarcodeScanner.stopScan();
      this.scanActive = false;
      this.dismiss();
    }
  }

  async checkPermission() {
    return new Promise(async (resolve, reject) => {
      const status = await BarcodeScanner.checkPermission({ force: true });

      if (status.granted) {
        resolve(true);
      } else if (status.denied) {
        const alert = await this.alertCtrl.create({
          header: 'Sem permissão',
          message: 'Por favor libere o acesso a sua câmera nas configurações.',
          buttons: [
            {
              text: 'Não',
              role: 'cancel',
              handler: () => {
                resolve(false);
              }
            },
            {
              text: 'Abrir configurações',
              handler: () => {
                BarcodeScanner.openAppSettings();
                resolve(false);
              }
            }
          ]
        });

        await alert.present();
      } else {
        resolve(false);
      }
    });
  }

  dismiss() {
    this.modal.dismiss();
  }

}

**Screenshots**
Here is the barcode I am trying to scan:
![WhatsApp Image 2021-09-06 at 12 08 24](https://user-images.githubusercontent.com/54998928/132237917-5230050f-feba-42c7-88ae-72bfc63f8d36.jpeg)

**Version**
 "@angular/core": "~10.0.0",
"@capacitor/android": "^3.1.2",
"@capacitor/core": "^3.1.2",
"@ionic-native/core": "^5.30.0",
"@ionic/angular": "^5.5.2",
"@capacitor-community/barcode-scanner": "^2.0.1"

**Smartphone (please complete the following information):**

- Device: ZenFone Shot Plus
- OS: Android 9

**Additional context**
When I scan a QR code it works perfectly but when I try to scan a barcode it doesn't work or it takes too long to read the barcode.

**Comment by ADMIADev** [comment]
the performance with barcodes is not very good. 
you can try out my pull request where its using the intergrator view which has better performance for barcodes.

**Comment by wash-dev** [comment]
@ADMIADev I'm still having trouble scanning barcodes. Could you please recommend some other plugin that is better for scanning barcodes?

**Comment by ADMIADev** [comment]
you could try implementing google ml for barcode scanning. 
https://developers.google.com/ml-kit/vision/barcode-scanning

**Comment by lehnihon** [comment]
Hi, i am having the same problem with barcode, so there is no other alternative to the capacitor right?

**Comment by ADMIADev** [comment]
did you try out the https://github.com/capacitor-community/barcode-scanner/pull/72 pullrequest i made? 
If you then set it to use integrator view in andorid it should work better.

**Comment by thegnuu** [comment]
I created a single issue to keep track of the 1D performance and will close this one :)
