### ISSUE TITLE
Issue when scanning a GS1-128 barcode

### ISSUE THREAD

**Issue by HunSpeedi** [capacitor-community/barcode-scanner#80]
**Description of the bug**
When I process a GS1 DataMatrix like this one:
https://barcode.tec-it.com/en/GS1DataMatrix?data=0105000456013482172012001000001%5CF210000000003
I get the following result: `\u001d0105000456013482172012001000001\u001d210000000003`
The **\F** (FNC1) terminator is recognized and the **\u001d** character is added between values.
However when I do the following with a GS1-128 barcode like this one:
https://barcode.tec-it.com/en/EANUCC128?data=010500045611225310COV0109%5CF17220901%20
I get the following result: `010500045611225310COV010917220901 `
And the **\F** (FNC1) terminator is not recognized and the values are concatenated.

**To Reproduce**
Scan the barcodes from the links above.

**Expected behavior**
The plugin should recognize the group separator in a case of a GS1-128 barcode as well.

**Version**
2.0.1

**Comment by tafelnl** [comment]
Do you experience this on both Android and iOS? Internally this library makes use of `AVFoundation` for iOS and `zxing` for Android ([read more here](https://github.com/capacitor-community/barcode-scanner#supported-barcodes)). So it might be that the implementation of those libraries is incorrect.

It could also be, that Capacitor somehow messes with these values when sending them from native to JavaScript.

Another cause could be that my implementation of some library is wrong.

**Comment by HunSpeedi** [comment]
I have experienced this on Android. I would guess that the `zxing` library causing the trouble (but ofc you can double-check your implementation as well), should I raise the issue on the page or you will do it?
Many thanks for the fast reply!!

**Comment by tafelnl** [comment]
If you could raise the issue there, that would be awesome!

**Comment by HunSpeedi** [comment]
I finally had some time to copy-paste the issue for them, let's see.
https://github.com/zxing/zxing/issues/1457

**Comment by thegnuu** [comment]
@HunSpeedi were you able to verify that the issues is caused by this plugin and not by `zxing`?

It seems like the issue you opened on `zxing` is closed now...

**Comment by HunSpeedi** [comment]
Hi @thegnuu !
I think the issue is on zxing side, there are some suggestions regarding using some hint, but I was not able to look after if it works or how we can use it in this package. If I will came across this again or have some more free time I will share my foundings here. Many thanks!

**Comment by thegnuu** [comment]
@HunSpeedi for your information, we are currently considering switching to `ML Kit` for this repo (#107).

It looks like `ML Kit` is able to detect `FNC1`, but not `FNC2`, `FNC3` and `FNC4` according to https://developers.google.com/ml-kit/vision/barcode-scanning.

Would this be sufficient for your usecase? As far as I know only `FNC1` is used at the beginning of `GS1-128` codes.

**Comment by HunSpeedi** [comment]
@thegnuu As far as I know it would not be an issue
