### ISSUE TITLE
UPDATE DOCS - FIX FOR Module '"@capacitor-community/barcode-scanner"' has no exported member 'BarcodeFormat'.

### ISSUE THREAD

**Issue by sagecoretech** [capacitor-community/barcode-scanner#85]
I fixed using 

`import { BarcodeScanner, SupportedFormat } from '@capacitor-community/barcode-scanner';`

and 

` const result = await BarcodeScanner.startScan({ targetedFormats: [SupportedFormat.QR_CODE] });`

Figured i would help community and submit this. It does seem to have a direct impact on performance to only be scanning for the supportedFormat wanted.

**Comment by tafelnl** [comment]
What exactly is your question/bug report? Targeting only specific formats is already mentioned in the docs here: https://github.com/capacitor-community/barcode-scanner#target-only-specific-barcodes

**Comment by sagecoretech** [comment]
Using the documented code to target specific formats throws error on ionic cap sync. 

See below output:

error TS2322: Type '"QR_CODE"' is not assignable to type 'SupportedFormat'.

88    const result = await BarcodeScanner.startScan({ targetedFormats: ['QR_CODE'] });

And the resolution is what i originally commented.

**Comment by tafelnl** [comment]
Closed by #86 . Do you agree?
