### ISSUE TITLE
Issue in adding a stop scan button and adjust the height and width of the camera

### ISSUE THREAD

**Issue by prasanthmarimi** [capacitor-community/barcode-scanner#91]
Hi,

I have used the plugin with my capacitor vue project where am trying to implement the barcode scanner. I found this one useful but after adding it, i released that i don't have any option to add a stop scan button over the screen(since camera covers all over the screen). Would be helpful if anyone can suggest me a solution where and how i can add a Stop button and also adjust the height and width of the camera view. Thanks.

**Comment by nesha14586** [comment]
Hi @prasanthmarimi I've put the button in the ion-footer. I'm using ionic/capacitor with angular. Please see below:

```
<ion-footer [hidden]="!scanActive">
  <ion-button expand="full" (click)="stopScanner()">
    Close
  </ion-button>
</ion-footer>
```

And then in the .ts file, the function is:

```
stopScanner() {
    BarcodeScanner.stopScan();
    this.scanActive = false;
 }
```

**Comment by thegnuu** [comment]
Since we have not heard from you @prasanthmarimi I guess you were able to fix your issue. If not feel free to reopen it and let us know what's not working for you :)
