### ISSUE TITLE
Cannot see camera view on dark mode (showing black screen)

### ISSUE THREAD

**Issue by nesha14586** [capacitor-community/barcode-scanner#96]
**Describe the bug**
Whenever I start the scan and show the camera view, on system dark mode, I only get black screen.
On light mode, everything is working fine.

**To Reproduce**

1. Change system theme to dark.
2. Start the scanner.

**Expected behavior**
Camera view would show.

**Screenshots**
![IMG_4272](https://user-images.githubusercontent.com/16090791/140762041-bf471ac5-0441-4406-a329-1f1df640c107.jpg)
![IMG_4273](https://user-images.githubusercontent.com/16090791/140762073-d88194d9-b0b2-41cb-8f94-987c77ded98d.jpg)

**Version**
^2.0.1

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro Max, iPhone 12 Mini
- OS: iOS 15.0.2

**Comment by rulaman123** [comment]
Same for me in Android. You have to make the body transparent:
`document.body.classList.add('qrscanner');`

in global.css:
```
body.qrscanner {
  background-color: transparent;
}
```

Working for both themes.
After scanning you can remove it:
`document.body.classList.remove('qrscanner');`

**Comment by jefaokpta** [comment]
Hi guys, i did it in this way:

startScan = async () => {
    console.log('startScan');
    this.isScanning = true;
    const body = document.getElementsByTagName('body')[0];
    body.style.backgroundColor = 'transparent';
...

<ion-content [fullscreen]="true" *ngIf="!isScanning">
...

this worked for me.

**Comment by nesha14586** [comment]
> Same for me in Android. You have to make the body transparent: `document.body.classList.add('qrscanner');`
> 
> in global.scss:
> 
> ```
> body.qrscanner {
>   background-color: transparent;
> }
> ```
> 
> Working for both themes. After scanning you can remove it: `document.body.classList.remove('qrscanner');`

Thanks dude, this solves it!
